### ISSUE TITLE
Heatmap: more detail

### ISSUE THREAD

**Issue by spacemansteve** [Japan-Digital-Archives/Japan-Digital-Archive#1015]
The indication of items on the map actually serves two purposes.  When there are hundreds or thousands of items, the heatmap provides a very efficient summary.  However, where there are only dozens or a hundred items a more accurate display is preferred.  This is especially important when very zoomed in.  Items may follow along individual roads or geographic features.  The current large size of the heatmap cells hides this fact.

At a minimum, we should increase the heatmap grid size when the user zooms in beyond some threshold.  This will provide more and smaller heatmap cells.  It would be better if whenever the number of items dropped below some threshold they were individually rendered.  This is beyond the scope of the project.  Steve will investigate implementing this feature using small red boxes.

It should be noted that both rendering more and smaller heatmap cells as well as rendering individual features will reduce performance.  Steve believes performance will be adequate.  

![heatmapmoredetail](https://cloud.githubusercontent.com/assets/957677/10758643/18f59542-7c89-11e5-9749-d12d85577f51.png)

**Comment by spacemansteve** [comment]
When there are few search results, displaying a heatmap doesn't convey useful information.  Instead, it is better to just render each item/Solr document.  This is not based on zoom level.  Whenever query filters or low data density causes the number of items to drop below 100, we draw a small red circle for each document.

![jdaheatmaprenderdocuments2](https://cloud.githubusercontent.com/assets/957677/11221090/3e47a6b0-8d31-11e5-98dc-567f86e99670.png)

![jdaheatmaprenderdocumentsusa](https://cloud.githubusercontent.com/assets/957677/11221093/44707896-8d31-11e5-8d5d-0921fb888a2a.png)

**Comment by horak** [comment]
Great! can this be closed then?

**Comment by spacemansteve** [comment]
detail view has been received well, it is available for testing at http://dev.jdarchive.org/heatmap/web/en/search#view_type=event&
