### ISSUE TITLE
Collection page: the save button is behind the create Waku button when editing the collection page

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1019]
http://jdarchive.org/en/collection/1475571
http://jdarchive.org/en/collection/1475579
![screen shot 2015-11-03 at 6 22 15 am](https://cloud.githubusercontent.com/assets/8831502/10895042/5a3eeabe-81f5-11e5-8e31-8897608ae230.png)

**Comment by rchen152** [comment]
This is caused by having too much text in the collection description - perhaps a CSS issue.

**Comment by jdaKoko** [comment]
When description sentence lines exceeds more than 4 or 5, the Waku boutton starts overlapping the save button.
I enlarged the webpage, the phenomenon happened.
![screen shot 2015-11-04 at 7 46 35 am](https://cloud.githubusercontent.com/assets/8831502/10924183/62cf9b50-82c8-11e5-9da8-b382d3a5be68.png)
![screen shot 2015-11-04 at 7 47 04 am](https://cloud.githubusercontent.com/assets/8831502/10924180/604e6c6c-82c8-11e5-91d5-e5b144c8b377.png)

**Comment by horak** [comment]
ah that's frustrating, I just don't have the bandwidth for anything that isn't mission critical right now unfortunately. The css I wrote for this is really simple. @jcuanm, do you think you could look at this?

**Comment by jcuanm** [comment]
I'm on it.

**Comment by jcuanm** [comment]
@jdaKoko @meeshmon 
Added a css property. Works fine in my system. Will close issue. 
@horak, pull request is ready.

**Comment by horak** [comment]
merged and live, nice work.
