### ISSUE TITLE
Cannot access bookmarklet on dev server

### ISSUE THREAD

**Issue by rchen152** [Japan-Digital-Archives/Japan-Digital-Archive#1021]
On dev, the website looks for the bookmarklet at http://dev.jdarchive.org/widget/, but the url should be http://dev.jdarchive.org/[NAME OF DEVELOPER]/web/widget/

**Comment by rchen152** [comment]
Fixed with https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/pull/1032

**Comment by horak** [comment]
:+1:
