### ISSUE TITLE
Bookmarklet: please remove "none" from image submissions

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1022]
When submitting images using the bookmarklet, the description field always shows "none".
Please remove "none" from the default setting.  It adds an extra work for users to delete "none" when  entering the description in the field.

![screen shot 2015-11-08 at 1 53 26 pm](https://cloud.githubusercontent.com/assets/8831502/11018856/4350f908-8620-11e5-8f30-34ffc92706dc.png)

**Comment by jcuanm** [comment]
@jdaKoko @meeshmon 
I've looked through the code and could not find any "none" text on the "Description" field.

When I tried to replicate the issue in the Bookmarklet the "none" text did not show.

Then I realize that your screen looks different than mine. If you take a look at my screen you
can see that your screen is missing two fields: Archive Frequency and Archive Scope.

Also, the "none" text is not showing in the Description field

Is it possible that you are running an older version of the Bookmarklet?? My screen-shot was taken directly from the production site.

![bookmarklet](https://cloud.githubusercontent.com/assets/8813674/11112217/a7577b0a-88c5-11e5-96ce-df5b5c3032cb.jpg)

**Comment by jdaKoko** [comment]
I just replaced the bookmarklet.  But it still show none and do not have scope and frequency. 
![screen shot 2015-11-12 at 6 45 01 pm](https://cloud.githubusercontent.com/assets/8831502/11115251/87a16a66-896d-11e5-92b8-47ad2e138d61.png)

**Comment by jdaKoko** [comment]
Do you have the new version of bookmarklet or the JDA website url?
I use http://jdarchive.org/en/home.

**Comment by jcuanm** [comment]
I am accessing:

When in Bookmarklet:     http://jdarchive.org/en/bookmarklet

When hitting "Add to JDA" button: http://jdarchive.org/widget/?title=......

**Comment by jdaKoko** [comment]
Do you have the bookmarklet in your bookmark tool bar?
You have to try submitting images from the bookmark tool bar clicking  "Add to JDA".
You can try submitting image using a url below.

![screen shot 2015-11-13 at 11 50 19 am](https://cloud.githubusercontent.com/assets/8831502/11137700/b6596170-89fd-11e5-9440-d19086950016.png)

![screen shot 2015-11-13 at 11 45 49 am](https://cloud.githubusercontent.com/assets/8831502/11137703/b9d4224a-89fd-11e5-9da9-8fb850f148e5.png)

http://wayback.archive-it.org/2438/20140813165911/http://www.jen-npo.org/memory/photo/20140812051433_p00000001.jpg

**Comment by jcuanm** [comment]
@jdaKoko
I made changes to the Bookmarklet. As soon as @horak performs the pull request, please test that 'None' does not show anymore.

**Comment by jcuanm** [comment]
@jdaKoko 
I will close this issue for now.

**Comment by jdaKoko** [comment]
@jcuanm @meeshmon 
I still do not see any change in the bookmarklet when I click Add to JDA on the toolbar. 
When I just click "Add to JDA" in the  http://jdarchive.org/en/bookmarklet/ page, it does not show "none".

There is a new problem.  The bookmarklet does not  connect to the collection, so that the users cannot make any collections.  My daughter and other volunteer could not access to the collection lists from the bookmarklet, either. I will post this problem as a new issue.

![screen shot 2016-02-26 at 7 09 05 am](https://cloud.githubusercontent.com/assets/8831502/13351959/312498f0-dc58-11e5-88ce-23dd66434aaa.png)
![screen shot 2016-02-26 at 7 09 27 am](https://cloud.githubusercontent.com/assets/8831502/13351960/32c306f6-dc58-11e5-929d-85f253f7ab20.png)

**Comment by meeshmon** [comment]
@horak still has not merged the fix Javier made, so this issue might be solved once it happens. The new issue I will have @jcuanm investigate.

**Comment by horak** [comment]
Sorry about the delay guys, @jcuanm I just posted a question in your pull request, can you take a look when you get a chance?
