### ISSUE TITLE
Investigate and fix dev server issues

### ISSUE THREAD

**Issue by rchen152** [Japan-Digital-Archives/Japan-Digital-Archive#1024]
We're frequently running into dev server problems when trying to troubleshoot bugs.

**Comment by horak** [comment]
Can you expound a bit? I think it might be more effective to post specific bugs that can be addressed.

**Comment by rchen152** [comment]
We created this issue during the tech meeting as a place we can list dev server issues so that they'll all be in one place.

**Comment by rchen152** [comment]
No longer necessary - we're using a label to mark dev server-related issues.
