### ISSUE TITLE
Collection:: A newly made collection disappeared from my collection box.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1028]
http://jdarchive.org/en/collection/2003109 does not appear in the Showa Boston Interns' collection box.

![screen shot 2015-12-01 at 7 54 20 am](https://cloud.githubusercontent.com/assets/8831502/11501458/4fa39a6e-9802-11e5-9c8d-f636e698fc88.png)
![screen shot 2015-12-01 at 8 14 49 am](https://cloud.githubusercontent.com/assets/8831502/11501665/ed50bbba-9803-11e5-886c-f70fd016f329.png)

**Comment by horak** [comment]
Is this still a problem @jdaKoko?

**Comment by horak** [comment]
bump @jdaKoko

**Comment by jdaKoko** [comment]
@horak 
I just edited the title of the collection from the page http://jdarchive.org/en/collection/2003109. Now I can see the collection title, below collection 228.  Thanks. 
http://jdarchive.org/en/collection/2003109
![screen shot 2016-02-08 at 4 18 37 pm](https://cloud.githubusercontent.com/assets/8831502/12899540/be0f7dc0-ce7f-11e5-987f-e965c6438181.png)

**Comment by horak** [comment]
:+1:
