### ISSUE TITLE
Please re-index: published items are not appearing in the JDA site.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1030]
Please reindex.  Newly published items are not appearing in the JDA site.

**Comment by meeshmon** [comment]
@horak can you quickly take care of this when you have a chance?

**Comment by horak** [comment]
Sorry reindexed, which items are you referring to?

**Comment by meeshmon** [comment]
Now nothing is showing up on the site. @jdaKoko can you tell Alex which items were missing?

**Comment by jdaKoko** [comment]
@horak @meeshmon 
Nothing is showing up now.  Previously,http://jdarchive.org/ja/user/1was not updating.

**Comment by meeshmon** [comment]
It's fixed now.

**Comment by jdaKoko** [comment]
@horak @meeshmon 
Tak,
Danke
Happy Holidays!
