### ISSUE TITLE
Yahoo images are disappeared from the admin page

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1033]
@meeshmon @horak 
Yahoo items (images) are disappeared from the admin page.
There should be 40,044 items, but now the JDA site only shows 19,284.
I am assuming id 2~ id 20760 are deleted from the admin page.
Yahoo user id 3
Yahoo page is http://jdarchive.org/ja/user/3
Corinne fixed the similar problem before.

**Comment by meeshmon** [comment]
@horak Looks like this problem can be fixed with re-indexing Solr once again.

**Comment by jdaKoko** [comment]
@meeshmon @horak 
I do not think she fixed this problem with re-indexing.  

The email below is a part of an email she sent Ryo and me in September 2014, when Yahoo images went missing.
I do not understand how she fixed the Yahoo image problem.
She maybe reimported the missing Yahoo data to the admin page.

---

I sent an email earlier giving details about what I'm doing with the Yahoo stuff - unfortunately my initial attempt created items with IDs 1839723~1908466, not the IDs we wanted (1-173123). 
I deleted all the items past 1839723, and then changed a bunch of the Zeega ingestion files, and ran a smaller test (just the first 2 items ever in our database!) this time so we wouldn't have so many wrong items.

And it worked! The 2 items I imported actually went into the ID slots 2 and 3 (what they were previously - I believe item 1 was a test item, it wasn't in our backup database). So now I have to get the other 170,000 items ingested. Unfortunately, I think I reached the server's cap on the amount of data I'm allowed to transfer for today, because it's not letting me upload anymore files right now. It might also be my connection - I'll keep trying later tonight.

**Comment by meeshmon** [comment]
My suggestion was meant to test the easiest possible solution prior to make this to a larger issue that we do not want to face. This is the part Corinne fixed by restoring a backup version of Amazon database. So I would suggest go with reindexing and if there is no improvement then try to restore the most recent backup, assuming the most recent backup is done in the beginning of this month.

**Comment by horak** [comment]
Ok, everything should be backup. Took me a while though and was a messy process. I'd like to document the process for posterity, i'll create an issue for that. 

![yahoo](https://cloud.githubusercontent.com/assets/1111424/12401938/c44237fc-bdf7-11e5-9fc0-20dc94cc5535.png)
