### ISSUE TITLE
Collection:: I cannot make a new collection.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1038]
I made a new collection, and  when I opened the collection, I got a message-- Oops! An Error Occurred
The server returned a "404 Not Found" Something is broken. Please e-mail us at info@jdarchive.org and let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

And  newly made collection id does not show up on the admin dash.

![screen shot 2016-01-17 at 8 57 41 pm](https://cloud.githubusercontent.com/assets/8831502/12381688/3b407d78-bd5d-11e5-87be-c502867c7ccc.png)
![screen shot 2016-01-17 at 8 58 06 pm](https://cloud.githubusercontent.com/assets/8831502/12381689/3cb21d06-bd5d-11e5-9d36-6ba174d6a2e7.png)

**Comment by horak** [comment]
Can you add things now?

**Comment by horak** [comment]
reported fixed.

**Comment by jdaKoko** [comment]
Thank you!
