### ISSUE TITLE
Data :: YouTube tags are off

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#104]
See: http://dev.jdarchive.org/staging/web/en/search#view_type=list&content=video&

**Comment by lfbrandao** [comment]
These tags seem correct to me. Check the source:

http://www.youtube.com/watch?v=vbBk0Y6cQZQ&amp;feature=youtube_gdata_player

Someone added some strange tags to this video on Youtube.
