### ISSUE TITLE
Please add names to the team page

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1046]
@jcuanm @horak @meeshmon 
 The same request as  #956 
Please add two names to the JDA team pages

To http://jdarchive.org/en/team
Content Development
Web Seed Curation: Mao Kuroda,  Showa Boston Institute for Language and Culture
Web Seed Curation: Rie Suzaki, Showa Boston Institute for Language and Culture

To http://jdarchive.org/ja/team
コンテンツ開発
ウェブシード　キュレーション：Mao Kuroda（昭和ボストン　黒田真央） 
ウェブシード　キュレーション：Rie Suzaki（昭和ボストン　須崎理絵） 

Yumiko Takeda, Kanami Ohno, and Maho Yanagisawa finished their internship on 1/6/16. Therefore, their names should be listed under Team Alumni.

English page: http://jdarchive.org/en/team
Yumiko Takeda, Showa Boston Institute for Language and Culture: Web Seed Curation
Kanami Ohno, Showa Boston Institute for Language and Culture: Web Seed Curation
Maho Yanagisawa, Showa Boston Institute for Language and Culture: Web Seed Curation

Japanese page: http://jdarchive.org/ja/team
under チームの卒業者
Yumiko Takeda（昭和ボストン　竹田有美子）: ウェブシード　キュレーション
Kanami Ohno（昭和ボストン　大野奏美）: ウェブシード　キュレーション
Maho Yanagisawa（昭和ボストン　柳澤真帆） : ウェブシード　キュレーション

**Comment by jcuanm** [comment]
I can take care of this.

**Comment by jcuanm** [comment]
@horak the merge is ready to be made

**Comment by horak** [comment]
@jcuanm, I'm not seeing the PR anywhere?

**Comment by jcuanm** [comment]
Sorry about that! Just made the PR.
