### ISSUE TITLE
Bookmarklet:: do connect to the collection lists

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1055]
@jcuanm @meeshmon 

The bookmarklet does not connect to the collection lists.

![screen shot 2016-02-26 at 7 09 05 am](https://cloud.githubusercontent.com/assets/8831502/13352117/3d4f5600-dc59-11e5-88d9-496c5dd25076.png)
![screen shot 2016-02-26 at 7 09 27 am](https://cloud.githubusercontent.com/assets/8831502/13352118/3e916954-dc59-11e5-98c1-c9f62049bff2.png)

**Comment by jcuanm** [comment]
I think I figured out the problem. Nothing is being passed into the select tag. The only thing we need to do is pass collections into the select tag as option tags. I will look more into this.

**Comment by jcuanm** [comment]
The path to the file is /src/JDA/CoreBundle/Resources/views/Widget/
