### ISSUE TITLE
Please post the Request for Proposal on the JDA website

### ISSUE THREAD

**Issue by meeshmon** [Japan-Digital-Archives/Japan-Digital-Archive#1057]
@horak @jcuanm @rchen152 
I would like to ask one of you to take care of this task ASAP. 
I have a pdf document of the Request for Proposal (RFP) to recruit potential developers that might be interested in helping the JDA to change/improve its current platform. 
I would like you to post the RFP by March 4th if possible by creating a new category "Project RFP" under "About" pull-down menu in the landing page so that whoever is interested can download the document from the page. 
If you can do that, please let me know. I will send you the pdf to work with.

**Comment by jcuanm** [comment]
I can take care of this. Do you want the "Project RFP" link to immediately download the pdf upon clicking, or do you want it to redirect the user to another page where they will click a link to download the pdf?

**Comment by meeshmon** [comment]
Thanks @jcuanm. Ideally I want to redirect the user to another page, but if it is hard, then you can take the click to download route.

**Comment by jcuanm** [comment]
I can't seem to figure out how to link to another file in twig. Is there some documentation on how to do this? Regular html doesn't seem to be working within a twig template.

**Comment by meeshmon** [comment]
@horak Do you know something?

**Comment by jcuanm** [comment]
The main problem I am having is that it doesn't recognize the path that I give it. I tried getting it to link me to facebook.com as a test, but it didn't recognize that either. Do we have to add our links somewhere else?

**Comment by horak** [comment]
Looks like you'll want to use `url` as opposed to `path`, as the later will only yield a relative link!

http://stackoverflow.com/questions/20393487/the-different-between-url-and-path-in-symfony2-3

**Comment by horak** [comment]
Let me know if you that works!

**Comment by horak** [comment]
Ok it's up!
