### ISSUE TITLE
Add Kahoku Shimpo to our partner page

### ISSUE THREAD

**Issue by meeshmon** [Japan-Digital-Archives/Japan-Digital-Archive#1063]
We have started ingesting items from Kahoku Shimpo (ID 656). 
Now I would like to add Kahoku Shimpo's description to the partner page (above Watanave, which still needs some writing). 
Please add below texts (both Japanese English) under the name 
**Kahoku Shimpo Disaster Archive**

河北新報は１８９７年、不羈独立と東北振興を社是として創刊しました。東北地方はたび重なる地震、津波被害を被りながらも、農林水産業を中心に日本の産業を支えてきました。２０１１年３月１１日に発生した東日本大震災は、わたしたちのふるさと東北に、甚大な被害を与えました。
　河北新報社は、被災地にある新聞社として「１０００年に一度」とも言われる大震災を後世に伝える国の「東日本大震災アーカイブ」プロジェクトに参加し、東北大学災害科学国際研究所の支援協力のもと、「河北新報震災アーカイブ」を立ち上げました。
新聞記事や報道写真のほか、市民の皆様が撮影した貴重な写真や動画なども収集・保存・整理し公開しています。震災の教訓が語り継がれ、今後の防災・減災に少しでも役立つよう、多くの皆様が利用しやすいサイトづくりを目指しています。

In March 11, 2011, the Great East Japan Disasters caused grave damage to our Furusato (hometown). As one of the oldest local newspaper companies in the disaster-stricken area that has been distributing papers to Tohoku region since 1897, Kahoku Shimpo participates in the “2011 Great East Japan Disasters Archive” national project in order to pass down the story of this “millennial-scale” disaster to future generations. Kahoku Shimpo Disaster Archive was launched in 2013 with technical assistance from the International Research Institute of Disaster Science at Tohoku University. Our archive collects, preserves and organizes not only newspaper articles and photographs we have published but also photographs and video footage that the local residents have generously contributed.. It is our wish that our archive be shared widely and that it aid in the generation of the stories and lessons learned from the disasters in 2011. Moreover, we hope to create an archive that is easy to use for all those who might utilize the records for disaster prevention and mitigation purposes.

**Comment by meeshmon** [comment]
@jcuanm This should be done by March 16th. If you cannot do so, I will ask others.

**Comment by jcuanm** [comment]
I will start working on this. It should be finished by the 16th.

On Sun, Mar 13, 2016 at 10:17 AM, meeshmon notifications@github.com wrote:

> @jcuanm https://github.com/jcuanm This should be done by March 16th. If
> you cannot do so, I will ask others.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/1063#issuecomment-195963366
> .

## 

Javier Cuan

**Comment by jcuanm** [comment]
@meeshmon the SolrMap parameters are preventing me from accessing my dev server. I have already addressed this with Steve. Depending on when he gets back to me, I do not know if I'll be able to get this done on time.

**Comment by meeshmon** [comment]
@jcuanm Hope you were able to fix the issue after Steve's email. If not can you ask Rebecca to do it instead?

**Comment by rchen152** [comment]
@meeshmon @jcuanm @jdaKoko I updated the partners page
Before I create a pull request, could you double-check that everything looks okay?  Kahoku Shimpo Disaster Archive is below Internet Archive and above metaLAB (at) Harvard.
http://dev.jdarchive.org/rebecca/web/en/partners
In particular, I'm wondering whether the title on the Japanese page should be Kahoku Shimpo in English or if it should be 河北新報震災アーカイブ.

**Comment by meeshmon** [comment]
@rchen152 thanks! Yes please put the Japanese name for the Japanese page. 
Otherwise looks good. Thanks

**Comment by horak** [comment]
Live!

**Comment by meeshmon** [comment]
Thank you all!
