### ISSUE TITLE
Search problem:: id 1828597 does not appear in search

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1071]
http://jdarchive.org/admin/zeega/data/item/1828597/edit
キッズドア被災者支援サイト – KIDS DOOR 復興 NET – 研修会　教員採用試験必勝講座（全５回）〜本気で教採に取り組む人のために〜 [pdf]

**Comment by horak** [comment]
Strange, this item doesn't seem to have a published attribute? Is that something you've seen before?

**Comment by jdaKoko** [comment]
Sometimes reindex solves the problem.

**Comment by horak** [comment]
Thanks Koko, we just had a tech meeting and discussed prioritizing these problems. Here's a quick short list of the plan!
1. reindex 
2. fix #1062, the missing Yahoo items
3. @spacemansteve will check if some of these items may have been lost in the heatmap transition period

**Comment by horak** [comment]
Ok, I've just re-indexed. Can you see if that made a difference @jdaKoko?

**Comment by jdaKoko** [comment]
@horak @meeshmon @spacemansteve 
Unfortunately, I still cannot see the item.  Now I cannot search items I recently edited through the admin edit page. Their item pages are all blank as well. These non-searchable items are related to the recent editing. I am guessing issues with #1073,#1071,#1070 are something with editing effects.

**Comment by horak** [comment]
Bummer. I will look into this in detail next week!

**Comment by horak** [comment]
Fixed!

**Comment by jdaKoko** [comment]
FYI 
http://jdarchive.org/admin/zeega/data/item/1828597/edit

I could not add tags from the edit page.
However, I was able to add a tag from the pop-up, but all attributes disappeared as I had mentioned in my email to you.
Then, I could add the second tag from the edit page.
