### ISSUE TITLE
311 memories :: 311 memories' 4/7/16 & 4/11/16 imports are not appearing on the JDA website.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1080]
311 memories' 4/7/16 & 4/11/16 imports are not appearing on the JDA website.
The re-index probably solves the problem.

**Comment by jdaKoko** [comment]
This is an update for the 311 memories' items.
15,684 items are not appearing on the JDA site.  April 7,11,14,18, 21, 25, 28 and May 2, 5, 9,12 &16 imports are not appearing.

**Comment by horak** [comment]
How can you tell these are missing?

I'm re-indexing now, i'll check after I'm done.

**Comment by jdaKoko** [comment]
Admin page user id 426 and the jda headline category numbers should match.
As of 5/17/16, the user id 426 total item number and the headline search number do not match.
![screen shot 2016-05-18 at 2 02 51 pm](https://cloud.githubusercontent.com/assets/8831502/15369638/846683f4-1d01-11e6-9bd7-bb5a9c6f9995.png)

**Comment by horak** [comment]
thanks! And how did you know the individual missing dates?

**Comment by horak** [comment]
Ok, the re-index looks like it's recovered all but 1 item

**Comment by jdaKoko** [comment]
Great!
I think, the1 item is the user collection which is not published.
Thank you very much!

**Comment by horak** [comment]
You're welcome!
