### ISSUE TITLE
Collection Page:: cannot delete items

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1089]
@meeshmon @horak
I tried to get rid of some items from the collection, http://jdarchive.org/en/collection/1997378
I cannot delete some of them.  I currently have 194 items in the collection id1997378.  I think I can delete first 100 items. After the 101th item, the remove sign does now show.
![screen shot 2016-04-27 at 3 04 53 pm](https://cloud.githubusercontent.com/assets/8831502/14864795/8913e33e-0c89-11e6-958d-45889a9a602b.png)

**Comment by horak** [comment]
@jdaKoko and refreshing doesn't change that?

**Comment by jdaKoko** [comment]
Nope, the same result.
![screen shot 2016-05-10 at 12 30 57 pm](https://cloud.githubusercontent.com/assets/8831502/15154378/37077110-16ab-11e6-92fc-59e0fc6e3bb5.png)

**Comment by horak** [comment]
Can you see if navigating away and returning to the page would fix this? Or logging out and back in? 

If you don't get to test those two things or don't want to, that's completely ok, i'm really backed up with issue #1086 right now, that's preventing a lot of other things from happening so I'm going to focus on that but I will look into this with more energy after that.

**Comment by horak** [comment]
from @jdaKoko:

> > To answers to the question above, neither procedure works.

**Comment by horak** [comment]
Hmm, ok investigating whether we put a limit on this.

**Comment by horak** [comment]
Fixed!
