### ISSUE TITLE
Team Page :: changes requested

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#1097]
@jcuanm @horak @meeshmon  The same request as #956 & #1046.

**＜Please add two names to the JDA team pages under 'Content Development'＞**
1.)　To http://jdarchive.org/en/team　
**Content Development**　　
Web Seed Curation: Natsumi Yasuda, Showa Boston Institute for Language and Culture
Web Seed Curation: Sarah Bush, Simmons College

2.) To http://jdarchive.org/ja/team 
**コンテンツ開発**
ウェブシード　キュレーション：Natsumi Yasuda（昭和ボストン　安田夏海） 
ウェブシード　キュレーション：Sarah Bush （シモンズ大学　サラ・ブッシュ）

**＜Mao Kuroda finished her internship. Therefore, her name should be listed under 'Team Alumni'＞**

3.) English page: http://jdarchive.org/en/team
 **Team Alumni**
Mao Kuroda, Showa Boston Institute for Language and Culture: Web Seed Curation

4.) Japanese page: http://jdarchive.org/ja/team
 **チームの卒業者**
Mao Kuroda（昭和ボストン　黒田真央）: ウェブシード　キュレーション

Thank you very much!

**Comment by jcuanm** [comment]
on it

**Comment by jcuanm** [comment]
Finished!

**Comment by jdaKoko** [comment]
Thank you @jcuanm, but I do not see the changes on the JDA site.
Sorry.

**Comment by jcuanm** [comment]
This is weird for me too... @horak does it take a while for a merge to take effect on the production site?

**Comment by jcuanm** [comment]
All of the changes seem to be added to the production code, but they still don't show on the actual site.

**Comment by meeshmon** [comment]
Javier, thank you for getting on this quickly. From the next time know, please close an issue once you see changes you made reflected on the live site. Hopefully soon we will see your work!

**Comment by jcuanm** [comment]
Ah! Sorry about that! I got excited

**Comment by horak** [comment]
@jcuanm, have you run the "release" script on production?

**Comment by horak** [comment]
Ah I see, yeah just merging on github doesn't push anything to production. [Here](https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/wiki/Contributing-to-the-archive-source-code#pushing-the-new-code-to-production) are instructions for doing that.

**Comment by jcuanm** [comment]
Awesome! I'll finish the job on Sunday. I can't get to it today

**Comment by jcuanm** [comment]
@horak How do I ssh into the production web server?

**Comment by horak** [comment]
All the instructions should be on the post above! If you have trouble with any specific step after consulting those, let me know. If you'd like, I can just take care of it as well?

**Comment by jcuanm** [comment]
The first thing the instructions say to do is to ssh into the production server. There are no further details. I know how to ssh into my own dev server but not into the production server. I'd like to learn how this is done.

**Comment by horak** [comment]
To ssh into the production server, type `ssh ubuntu@prod.jdarchive.org` into your terminal. The rest of the instructions should be there!

**Comment by horak** [comment]
And please remember to be careful! The server isn't the most resilient unfortunately.

**Comment by jcuanm** [comment]
How should I receive the password?

**Comment by horak** [comment]
Are you not able to log in? I thought we setup your ssh keys a while back.

**Comment by jcuanm** [comment]
When I type ubuntu@prod.jdarchive.org, it says that I need a password.

**Comment by horak** [comment]
ok, can you email me your public ssh key again?

**Comment by jcuanm** [comment]
I'll send them immediately, but seeing as this might take longer than expected, could you push the changes to production please?

**Comment by horak** [comment]
Done, should be live.

**Comment by jdaKoko** [comment]
@horak @jcuanm 
I confirmed the changes. Thank you very much.
