### ISSUE TITLE
JDA - time/date slider boxes cropped at top

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#12]
date-time-start and date-time-end are often clipped by div above it? Perhaps white-background-search? Noticeable in Chrome OS X but worse in other browsers. Moved from the Zeega repository - https://github.com/Zeega/Zeega-Core/issues/492

**Comment by kanarinka** [comment]
ee00049f3f7ff6984e8193656c178eb81ee2d8cc

Lindsey Filipe or Konrad - Could you check on your larger monitors to see if this is fixed? 
http://dev.zeega.org/kanarinkajda/web/en/search
I can't tell from my small monitor.
