### ISSUE TITLE
JDA - Layer buttons left aligned, but layer names right aligned

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#13]
Map layer tab:

The checkboxes are aligned left, but the names of the layers are aligned right. Looks strange.

bootstrap.css 
@ line 624 

delete text-align:right? Moved from the Zeega repository - https://github.com/Zeega/Zeega-Core/issues/491

**Comment by kanarinka** [comment]
b002944980d12d5b04d7eb1b46bfb18fd9a05200
