### ISSUE TITLE
Tags on YouTube videos not broken into individual tags

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#136]
All seems to be one big list. For example, on first video:

Nonprofit,宮城県仙台市若林区荒井,七郷小学校,津波,震災体験,避難所,東日本大震災,３がつ１１にちをわすれないためにセンター,せんだいメディアテーク

**Comment by lfbrandao** [comment]
The problem seems to be on the Fancybox; the data is correct http://dev.jdarchive.org/zeegastaging/web/api/search?content=Video
