### ISSUE TITLE
Pasting text into to search box on home page obscures all but last few characters

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#137]
To replicate:

go to home page (in chrome os x).
click in search box, 
paste text "futaba hospital" into the search box
note that it is almost invisible.

pressing spacebar will return it to visibility but may confuse visitors.

**Comment by hsenju** [comment]
I tested this out and I think this is more of an issue with visualsearch.js than our code.
I got the same issue when pasting things into
http://documentcloud.github.io/visualsearch/
When you click outside of the searchbox, the pasted text appears in full.
