### ISSUE TITLE
Quotations required with tags that have multiple words?

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#138]
Currently if you search tag:foreigners leaving japan you get 0 hits.

If you search tag:"foreigners leaving japan" you get the correct number 2.

Is that by design? 

Regardless remains following problem:

If you search tag:foreigners 

you get 12 hits but none of them include the 2 items tagged: foreigners leaving japan

Surely, partial search with foreigners should also return tags with foreigners leaving japan?

**Comment by kmlawson** [comment]
Compare search with: http://jdarchive.org/seeds/?t=foreigners%20leaving%20japan

**Comment by lfbrandao** [comment]
Thanks Konrad, this was definitely an issue and helped me detect another problems on the search queries. Should be fixed now.

**Comment by kmlawson** [comment]
Glad to hear it!
