### ISSUE TITLE
jda.search.data

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#14]
When opening the map layer tab jda.search.data is shown next to legend. This should probably be something else no? Like "Layers" or some such? Moved from the Zeega repository - https://github.com/Zeega/Zeega-Core/issues/490

**Comment by kanarinka** [comment]
ee00049f3f7ff6984e8193656c178eb81ee2d8cc

Jesse can you add a japanese translation for jda.search.data? then this issue should be closed
