### ISSUE TITLE
after logging in, there is a drop down menu with user options in top right but no label for it

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#170]
add a label? Call it "settings" or something? Up to you.

**Comment by jamesburns** [comment]
You may be loggin in with a user that has no display name. Registering a new user with display name will populate this menu.

**Comment by kmlawson** [comment]
Ah I see. This will likely be unclear for all the hundreds of people transferred over from the Alpha. How should we deal with this?
