### ISSUE TITLE
JDA - tweets in list on map only show thumbnail which isn't helpful. Can we show the actual tweet?

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#18]
Moved from the Zeega repository - https://github.com/Zeega/Zeega-Core/issues/482

**Comment by kanarinka** [comment]
9dc7771a80bff3ac9f569f74f1e5a90e262e6cad

We can do custom formatting for other media types in the map popup as well so let me know if you want to customize anything else.
