### ISSUE TITLE
User search should be for display name not email (aka username)

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#188]
Searching user: jms does not return results. Possibly linked to collections all being displayed as by "Unknown."

**Comment by lfbrandao** [comment]
Seems to work for mine  - User: luisbrandao@gmail.com. Are you sure jms is your username? I think it should be an email if you created it recently.

**Comment by jshapins** [comment]
Ah - jms is what shows up in header when I'm logged in. Not a high priority, but worth thinking about.
