### ISSUE TITLE
JDA - Search bar bugs in time/place view

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#19]
i can remove the date and time filter but this doesn't take me back to list view? so if i search for something, select a related tag or filter for a format (like audio) that doesn't have time and place data, I see a number of results and no points on the map? Moved from the Zeega repository - https://github.com/Zeega/Zeega-Core/issues/481

**Comment by kanarinka** [comment]
Hi all - I've fixed this somewhat by updating the CQL query which wasn't parsing the search query correctly, however there is still an issue viewing tags. Filipe - should the CQL for tags be 

tags='jishin' ? It's returning all sorts of weird errors when I try this. 

Also, what would the syntax be for multiple tags?

Thanks!

**Comment by kanarinka** [comment]
H847ab5a59b22b9f6e459bdb6059ee84cba104e60
