### ISSUE TITLE
JDA - Confirm Korean functional for testimonial search

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#23]
[In this previous issue](https://github.com/Zeega/Zeega-Core/issues/417) it was mentioned that a search for 사람 did not show anything up. Is it possible all Korean search is broken? Or that not all testimonials were imported?

Here are some example testimonials that should be in your database that you can pull text out of to run test searches:

Korean:

http://jdarchive.org/testimonial/public/57/53514320f075?la=ja
http://jdarchive.org/testimonial/public/64/e9a827589370?la=ja
http://jdarchive.org/testimonial/public/60/223f0e6ae15f?la=ja
http://jdarchive.org/testimonial/public/59/65c01b2387a6?la=ja
http://jdarchive.org/testimonial/public/57/53514320f075?la=ja

Chinese example:

http://jdarchive.org/testimonial/public/32/714611f1665a?la=ja
 Moved from the Zeega repository - https://github.com/Zeega/Zeega-Core/issues/467

**Comment by kmlawson** [comment]
this appears to still be a problem, 0 hits for 사람 - suggest we hand this over to Arne to look into.
