### ISSUE TITLE
JDA - change datetime formatting when interface in Japanese

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#24]
[YEAR]年[MONTH]月[DAY]日[HOUR]時[MINUTE]分 

in PHP date() format:

date("Y年n月j日G時i分"); Moved from the Zeega repository - https://github.com/Zeega/Zeega-Core/issues/466

**Comment by kmlawson** [comment]
great to see this revived!
