### ISSUE TITLE
allow user to edit archive settings

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#302]
Can't seem to find the option to make the collection public or not.

**Comment by jshapins** [comment]
This is complicated on the backend. Will try to have for release, but I think a more likely early feature post-launch.

**Comment by jshapins** [comment]
The UX for this modal is on page 2: https://docs.google.com/file/d/0B74ovMvsoNaZeVM3b3ZJaUdOX2s/edit
