### ISSUE TITLE
in Japanese version of collection page jda-collection-filter-new overlaps search bar

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#303]
all of these styling issues with Japanese are because you are treating font sizes same in Japanese and English.

Always make Japanese font slightly smaller than English font:

https://github.com/Zeega/Japan-Digital-Archive/issues/257

for now, I can fix it by changeing #jda-collection-filter-new top: 95px on Japanese version

**Comment by jshapins** [comment]
Same as #280
