### ISSUE TITLE
first collection on cover page links to wrong collection

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#307]
see emails from Eric to Jesse

**Comment by jshapins** [comment]
Fisheries: id=885024 / http://dev.jdarchive.org/james/web/en/search#view_type=list&collection=885024&content=all&
Rebuilding: id=884991 / http://dev.jdarchive.org/james/web/en/search#view_type=list&collection=884991&content=all&
Food Supply: id=885007 / http://dev.jdarchive.org/james/web/en/search?#view_type=list&collection=885007&content=all&
