### ISSUE TITLE
Tweets on map view show only thumbnail when clicked

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#31]
I think there used to be an issue for this but I must be missing it...

**Comment by kanarinka** [comment]
I closed this because it should be fixed

On Wednesday, March 14, 2012, K. M. Lawson <
reply@reply.github.com>
wrote:

> I think there used to be an issue for this but I must be missing it...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Zeega/Japan-Digital-Archive/issues/31

## 

---

www.kanarinka.com    ||    kanarinka@ikatun.org    ||    617-501-2441

---

**Comment by jshapins** [comment]
James/Filipe, is there a merged version where this is working?
