### ISSUE TITLE
problem again of map showing items not permitted by filter

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#310]
as of this morning, if you search 漁業, switch to map and filter by image by only, you still get websites on map

**Comment by jshapins** [comment]
what branch are you testing on?

On Thu, Jun 28, 2012 at 11:13 AM, K. M. Lawson <
reply@reply.github.com

**Comment by kmlawson** [comment]
staging…I guess I should check this on james jesse and joseph?

**Comment by jshapins** [comment]
Test on james.

On Thu, Jun 28, 2012 at 11:15 AM, K. M. Lawson <
reply@reply.github.com

**Comment by kmlawson** [comment]
works fine…

**Comment by jshapins** [comment]
Works on james branch, which will be merged, so I'm closing this issue.
