### ISSUE TITLE
FF Mac :: audio doesn't load in fancybox

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#339]

**Comment by kanarinka** [comment]
Do you mean audio doesn't load in collections player? Is this the same bug as 347 -- https://github.com/Zeega/Japan-Digital-Archive/issues/347?

**Comment by jshapins** [comment]
Related, but distinct. This issue refers to audio in the fancybox.

On Mon, Jul 2, 2012 at 11:14 AM, kanarinka <
reply@reply.github.com

**Comment by jamesburns** [comment]
FYI, another issue may be directly referenced in the comments with "#", e.g. #347, which automatically creates a link

**Comment by kanarinka** [comment]
Hey all - I've spent almost an hour digging around on this one and wanted to check in before going further. This is also an issue for playing videos in FF (at least YouTube videos, not sure about HTML5). It's not a fancybox bug, it's related to the popcorn player. You can see here how the individual item page also doesn't load in Firefox: http://dev.jdarchive.org/kanarinka/web/en/item/884914

What's happening is that the events that popcorn is listening for like 'loadeddata' and 'canplaythrough' (see line 204 of plyr.js) are not firing in Firefox so the Popcorn player & controls never finish loading and they also don't give any error message. 

It looks like there's a newer version of Popcorn so perhaps we should try that? I'm happy to try to switch it in but noticed it was highly configurable and didn't want to mess up anything else that core Zeega uses or that you have planned for the future -- http://mozillapopcorn.org/build-tool/ -- just let me know how you want me to proceed with this.
