### ISSUE TITLE
Create new fancybox view for linked PDF document

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#367]

**Comment by jshapins** [comment]
Instead of displaying a thumbnail or iframe for the item, display a generic PDF icon and copy that says "Click to download PDF" which opens new window with link to URL w/ .pdf at the end. (For now, there are no PDFs in the database, so just set the link to access the source URL for the item).

**Comment by kanarinka** [comment]
Made the PDF view and linked it to images for the moment for testing:
http://dev.jdarchive.org/kanarinka/web/en/search#content=image&

Let me know if it looks good and then I'll set images back to the image view
