### ISSUE TITLE
Make collections description not limited in characters

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#370]

**Comment by jshapins** [comment]
Make it possible for the description to be as long as any user wants.

**Comment by kanarinka** [comment]
This is a DB issue -- the front-end doesn't put any limit on it. Here's what the DB says:

SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(500)
[1] PDOException: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(500)

**Comment by lfbrandao** [comment]
Would it be possible to write the description on the 'text' field for collections and load this field instead for collections only?

**Comment by kanarinka** [comment]
That shouldn't be a problem - I will change that on the front end now
