### ISSUE TITLE
Add “Team Page”

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#372]

**Comment by jshapins** [comment]
This would be a dropdown from About and open a new page (doesn't need to be a hashed page) that includes this content:

https://docs.google.com/document/d/14NLm9pZ3Vi-AA2G7Jq_0ZX82ENZzAFinKXPBuJCUYig/edit

**Comment by kanarinka** [comment]
There is one person who needs a title on here --Stacie Matsumoto -- and there are some minor inconsistencies with people's titles if that matters -- otherwise - done --
http://dev.jdarchive.org/kanarinka/web/en/team
