### ISSUE TITLE
Add link to Seed + Testimonial forms from “About dropdown”

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#373]

**Comment by jshapins** [comment]
I think we should add a button to the header that says "Add to the Archive." It would be to the right of "Give us Feedback." It has two dropdowns. One is "Add a Website" the other is "Add a Testimonial." 

The website link opens a new window with: http://jdarchive.org/contribute/?la=en
Testimonial opens a new window with: http://jdarchive.org/testimonial/?la=en

**Comment by kanarinka** [comment]
this is done
