### ISSUE TITLE
Localization of updated header

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#390]
Add to the Archive
-> Add a web site
-> Add a testimonial
About the archive

Waiting on translations from Taisei in this file:

https://docs.google.com/spreadsheet/ccc?key=0Ail66ogxnZeLdHpXaXpZU0dqMWttRlBpYTdHRWVqTUE#gid=0

**Comment by nickkapur** [comment]
These translations have been added, plus a few more.
