### ISSUE TITLE
duplicate items in collections

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#399]
My collection contains duplicate items, although I only added the item once.

**Comment by lfbrandao** [comment]
Hi @mollydesjardin - is this still happening for you? I saw that you created today a similar issue #441 and I made some fixes, but I can't reproduce it.

**Comment by mollydesjardin** [comment]
Hi @luisbrandao . This is still happening. It's happening in my collection, and you can see it most easily by identifying the duplicate testimonial. Basically, there is a list of items with for example "via RIJS" and then they are duplicated and attributed "via Molly Des Jardin" after that.

http://jdarchive.org/ja/collection/885250
