### ISSUE TITLE
Contribute :: form debug

### ISSUE THREAD

**Issue by lfbrandao** [Japan-Digital-Archives/Japan-Digital-Archive#407]
- error message if the fields are empty or something goes wrong
- can't submit the form

**Comment by ebensing** [comment]
all of these issues are fixed although form submission is not working get the following error when I try to POST to the api end point:

{"message":"Catchable Fatal Error: Argument 1 passed to Zeega\DataBundle\Entity\Item::setUser() must be an instance of Zeega\DataBundle\Entity\User, string given, called in \/var\/www\/zeega\/src\/Zeega\/DataBundle\/Service\/ItemService.php on line 24 and defined in \/var\/www\/zeega\/src\/Zeega\/DataBundle\/Entity\/Item.php line 869","class":"ErrorException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/zeega\/src\/Zeega\/DataBundle\/Entity\/Item.php","line":869,"args":[]},{"namespace":"Symfony\Component\HttpKernel\Debug","short_class":"ErrorHandler","class":"Symfony\Component\HttpKernel\Debug\ErrorHandler","type":"->","function":"handle","file":"\/var\/www\/zeega\/src\/Zeega\/DataBundle\/Entity\/Item.php","line":869,"args":[["string","4096"],["string","Argument 1 passed to Zeega\DataBundle\Entity\Item::setUser() must be an instance of Zeega\DataBundle\Entity\User, string given, called in \/var\/www\/zeega\/src\/Zeega\/DataBundle\/Service\/ItemService.php on line 24 and defined"],["string","\/var\/www\/zeega\/src\/Zeega\/DataBundle\/Entity\/Item.php"],["string","869"],["array",{"this":["object","Zeega\DataBundle\Entity\Item"]}]]},{"namespace":"Zeega\DataBundle\Entity","short_class":"Item","class":"Zeega\DataBundle\Entity\Item","type":"->","function":"setUser","file":"\/var\/www\/zeega\/src\/Zeega\/DataBundle\/Service\/ItemService.php","line":24,"args":[["string","anon."]]},{"namespace":"Zeega\DataBundle\Service","short_class":"ItemService","class":"Zeega\DataBundle\Service\ItemService","type":"->","function":"parseItem","file":"\/var\/www\/zeega\/src\/Zeega\/ApiBundle\/Controller\/ItemsController.php","line":207,"args":[["array",{"title":["string","this is my blog"],"description":["string","this is my blog"],"media_type":["string","Website"],"layer_type":["string","Website"],"uri":["string","http:\/\/rm-dash-r.com"],"attribution_uri":["string","http:\/\/rm-dash-r.com"],"media_creator_username":["string","Not Given"],"media_creator_realname":["string","Not Given"],"media_geo_latitude":["string","42.3736158"],"media_geo_longitude":["string","-71.1097335"],"language":["string","English|"],"attributes":["array",[["string","frequency:Once"],["string","scope:Page"]]],"published":["string","0"]}],["string","anon."]]},{"namespace":"Zeega\ApiBundle\Controller","short_class":"ItemsController","class":"Zeega\ApiBundle\Controller\ItemsController","type":"->","function":"postItemsAction","file":null,"line":null,"args":[]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func_array","file":"\/var\/www\/zeega\/app\/bootstrap.php.cache","line":1421,"args":[["array",[["object","Zeega\ApiBundle\Controller\ItemsController"],["string","postItemsAction"]]],["array",[]]]},{"namespace":"Symfony\Component\HttpKernel","short_class":"HttpKernel","class":"Symfony\Component\HttpKernel\HttpKernel","type":"->","function":"handleRaw","file":"\/var\/www\/zeega\/app\/bootstrap.php.cache","line":1385,"args":[["object","Symfony\Component\HttpFoundation\Request"],["string","1"]]},{"namespace":"Symfony\Component\HttpKernel","short_class":"HttpKernel","class":"Symfony\Component\HttpKernel\HttpKernel","type":"->","function":"handle","file":"\/var\/www\/zeega\/app\/bootstrap.php.cache","line":1561,"args":[["object","Symfony\Component\HttpFoundation\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\Bundle\FrameworkBundle","short_class":"HttpKernel","class":"Symfony\Bundle\FrameworkBundle\HttpKernel","type":"->","function":"handle","file":"\/var\/www\/zeega\/app\/bootstrap.php.cache","line":612,"args":[["object","Symfony\Component\HttpFoundation\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\Component\HttpKernel","short_class":"Kernel","class":"Symfony\Component\HttpKernel\Kernel","type":"->","function":"handle","file":"\/var\/www\/zeega\/web\/app_dev.php","line":17,"args":[["object","Symfony\Component\HttpFoundation\Request"]]}]}]

**Comment by lfbrandao** [comment]
By default only logged users can post to the API; I'll make an exception for this.
