### ISSUE TITLE
Additional websites have not yet been added

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#425]

**Comment by nickkapur** [comment]
We need to run the script to add the full list of archived websites to the archive. Search is still returning only ~8900 websites.

**Comment by lfbrandao** [comment]
They are on the archive, but marked as private. I assumed that you would update them after the submission to IA (I believe some of the websites haven't been submitted yet and we have been using exclusively the IA version of each website). 

What's the best way proceed?

**Comment by nickkapur** [comment]
There were about 15,000 sites which were already archived by IA, so those we should definitely find a way to make those public. There were about 1000 sites which were approved but not yet submitted to IA. We need to figure out how to export those to a csv file and send them to IA.

**Comment by nickkapur** [comment]
Andy would really like all of the sites that are already archived by IA to be publicly available through our archive. EJ will email you very soon with the seed number up through which all sites are already in IA and we can switch those to public.

**Comment by lfbrandao** [comment]
This can be fixed easily - let me know which ids should be public.
