### ISSUE TITLE
Advanced search :: advanced search item types not maintained when resorting by different criterion

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#429]

**Comment by lfbrandao** [comment]
This happens because outside the advanced search form, the search by media type is done using a dropdown and there's no way to select more than one item on it. How do you see this working?

**Comment by nickkapur** [comment]
I don't mean resorting by media types. I mean resorting by "relevance" "oldest" or "recent". Sorry for not being more clear. Certainly an advanced search should still be resortable in these ways, right? At present, if you resort to "oldest" or something, it switches to searching all media types.
