### ISSUE TITLE
Collections :: Clicking on "Go to My Collection" from main search screen gives a 404 message

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#435]

**Comment by lfbrandao** [comment]
Can you tell for which collection this is happening? The collection name should be enough for me to find it.

**Comment by nickkapur** [comment]
It was happening yesterday when I dragged objects into the box as if to create a new collection. But I can't replicate the bug today so I'm going to close this issue for now.
