### ISSUE TITLE
user email displayed on user-submitted items' "view source"

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#437]
From user:

I also noticed that if the submitter enters an email address on the submission, the email address is revealed next to 「元の情報を開く」("View source") on the lefthand side.
I would like to erase my personal email address when people see the website in order to prevent spam or other problems.

**Comment by jamesburns** [comment]
A link to an example of this issue would be helpful in resolving.

**Comment by mollydesjardin** [comment]
@jamesburns 

From user:

As I mentioned before, some of the Koko Howell's collections and edited collections are currently lost, so I cannot give the exact page in which I saw the personal email appearing problem.
Instead, I will give an example from Eric Dinmore's collection.  The collection is open to the public so that the Zeega people do not have to sign in.

Go to http://beta.jdarchive.org/en/search#view_type=thumb&media_type=Collection&
Please click  Fukushima and the Food supply http://beta.jdarchive.org/en/collection/885007

Click mphoto-2011-03-27T21:12:53-2.jpg., then a fancy box box appears.
At the bottom of the fancy box you can see the Eric's email address next to 　”View Source”.
ericdinmore@fas.harvard.edu
