### ISSUE TITLE
collection items duplicated in list view

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#441]
From user:

"When I created my collections and checked the thumbnails for each collection, it would correctly list the number of seeds--so if there were 15 seeds, there'd be 15 thumbnails. However, when I looked at the list view, every seed was duplicated--so a listing of 30 seeds instead of 15, with one instance marked as via Koko Howell and the other as via RIJS in blue text."

**Comment by lfbrandao** [comment]
Can I get the user name or email, please?

**Comment by mollydesjardin** [comment]
@luisbrandao The email is khowell60@gmail.com
