### ISSUE TITLE
duplicate tweets display no text

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#468]
There are some duplicate tweets that say "via [username]" instead of "via Hypercities," and are blank. For example, if you filter all items by "tweets" and order by newest, you will see a number of tweets that are "via Molly Des Jardin" and are blank.

**Comment by lfbrandao** [comment]
The empty tweets don't seem to exist on the production site http://jdarchive.org/en/search#media_type=Tweet&sort=date-desc&, but I'm seeing a few duplicates. I will take a look at this later.
