### ISSUE TITLE
duplicate items from collections - via "[username]" of [username]'s collection

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#469]
When filtering all items by "Documents," you can see that there are several duplicates at the top (when ordered by newest first), "via Molly Des Jardin," "via Taisei Wake," "via Koko Howell," "via Ted Gilman." These are all duplicates and I think the problem stems from them being included in a collection. If you scroll down you can see that "Fukushima Fallout Markey Report" is "via Ted Gilman" and also "via RIJS."

**Comment by lfbrandao** [comment]
Link to #468 (check what's going on with these duplicates). This exact issue only happens on development, but I am seeing some duplicates on the production site and will investigate.
