### ISSUE TITLE
dummy web sites in archive should be removed

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#470]
There are several dummy web sites listed as the newest web sites when filtering all items by "website." Here is a screenshot of the sites. They should be removed from the site.

![Screen Shot 2013-01-23 at 11 27 41 AM](https://f.cloud.github.com/assets/2146722/90555/fb4a1c12-6579-11e2-9cdc-3fb66af227d1.png)

**Comment by lfbrandao** [comment]
Not an issue on jdarchive.org  (only in development because we're using a test database).
