### ISSUE TITLE
can't log into the web site using chrome; password reset gives 500 error

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#471]
I can't log in to the site using Chrome on Mac OS 10.7, and when clicking on "reset my password" after entering my email I get the following error message:

Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please e-mail us at [email] and let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by lfbrandao** [comment]
Should work on the dev server again - let me know if user issues are stopping you from testing. I can also change your password manually.
