### ISSUE TITLE
Item editor on admin not working on /staging/

### ISSUE THREAD

**Issue by ebensing** [Japan-Digital-Archives/Japan-Digital-Archive#480]
http://dev.jdarchive.org/staging/web/admin/zeega/data/item/4/edit 

works on: http://dev.jdarchive.org/ej/web/admin/zeega/data/item/4/edit and worked when changes were first merged into staging.

**Comment by lfbrandao** [comment]
It's working now. I merge stable into staging and fixed a small issue (https://github.com/Zeega/Japan-Digital-Archive/commit/90642f68f386b80c08f0800ffc6c56acd09c7c9f)
