### ISSUE TITLE
user page does not display profile in English version

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#482]
Going to the URL:

http://jdarchive.org/en/user/409

Only intermittently displays the user profile (usually only the list of collections/items the user has made) and when the profile is displayed, does not have an icon to edit the profile. Accessing through the Japanese version works without a problem. This is my profile and I'm using the URL while logged in.
![Screen shot 2013-01-28 at 11 05 05 AM](https://f.cloud.github.com/assets/2146722/103565/1019f556-6965-11e2-9f19-06aa14e060e0.jpg)

**Comment by jshapins** [comment]
@mollydesjardin I'm not able to replicate this. Profile works consistently in both English and Japanese versions, when I'm both logged in and logged out. Does the problem persist for you? Other users?
