### ISSUE TITLE
user name and "via" attribution not showing in collection view, unless filtering by text search

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#483]
A user, both logged in and out, noticed that her name is not showing as the creator of the collection and on individual items, the "via" attribution is empty (collection # 1475646). In another collection (#913915) her name is showing as the creator of the collection, but "via" is still empty. In 

However, when searching within the collection, the user name and "via" both show up. When searching the entire archive with a regular text search, "via" attribution does show up.

See screenshots.

![Screen shot 2013-01-30 at 10 46 00 AM](https://f.cloud.github.com/assets/2146722/111389/33627e44-6af4-11e2-811e-916718788d52.jpg)

![Screen shot 2013-01-30 at 10 47 05 AM](https://f.cloud.github.com/assets/2146722/111391/55802b16-6af4-11e2-95e5-7543152b11ad.jpg)

![Screen shot 2013-01-30 at 10 48 28 AM](https://f.cloud.github.com/assets/2146722/111405/854ff164-6af4-11e2-8c84-627a6b783e28.jpg)

![Screen shot 2013-01-30 at 10 48 50 AM](https://f.cloud.github.com/assets/2146722/111408/927513f6-6af4-11e2-8281-c830344807b2.jpg)

**Comment by jshapins** [comment]
I've tested and validated that this is a bug.
