### ISSUE TITLE
Search results never loaded on Safari

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#485]
When either searching the entire archive, for a term, or looking at a collection, the results of the search never show up in Safari 5 on OS 10.6.8. See screenshots. Is this version of the browser being supported?

![Screen shot 2013-02-04 at 1 49 38 PM](https://f.cloud.github.com/assets/2146722/124736/148cd6c0-6efc-11e2-8209-6f997f68d1f9.jpg)
![Screen shot 2013-02-04 at 1 50 01 PM](https://f.cloud.github.com/assets/2146722/124737/181a340e-6efc-11e2-81f4-7d8f1bc957c4.jpg)

**Comment by nickkapur** [comment]
Everything looks fine on Safari 6. I'm not going to worry too much about Safari 5 at this point.
