### ISSUE TITLE
Documentation needed for checking for duplicate items in database when ingesting data

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#486]
Some data requires checking to make sure it is not already in the database before ingesting. Documentation is needed on how best to do this in the ingestion process (include in wiki page?).

**Comment by lfbrandao** [comment]
See 4. of "General data import workflow" at https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/wiki/Adding-data-to-the-archive
