### ISSUE TITLE
No results display on map of collections

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#487]
When in map view on the "collections" main page, the map says that 50 results with map coordinates are available, but does not display any dots on the map that I could find. On individual collections, even those with map data, the map icon disappears and collections aren't able to be viewed in map view.

**Comment by jshapins** [comment]
This is a feature. @jameburn, to achieve this, is it required for Todd to complete the SOLR connector?

**Comment by nickkapur** [comment]
This works now.
