### ISSUE TITLE
Zeega player: "document" items are skipped in slideshow

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#488]
In Zeega player slideshows, "document" item types are not displayed in the slideshow at all.  For example, in http://jdarchive.org/ja/collection/1194843 slideshow, 全内漁連機関誌　ぜんない　第２２号-PDF is never displayed. (Only 4 of 5 items are displayed in the slideshow.)

**Comment by nickkapur** [comment]
This was a feature and not a bug, apparently.
