### ISSUE TITLE
Zeega player: slideshow does not start if collection begins with "document" or "article" item

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#489]
If a collection begins with an item of "document" or "article" type (ex: 311 memories headline), the slideshow never begins in Zeega Player for that collection. See http://jdarchive.org/ja/collection/1475627 and http://jdarchive.org/ja/collection/1475706 for examples.

**Comment by nickkapur** [comment]
Player is mothballed for now.
