### ISSUE TITLE
Zeega player: "testimonial" items display only "Text" instead of actual text of testimonial

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#490]
In the Zeega player, testimonial items do not display properly. They display the text "Text" in red instead of displaying the actual text of the testimonial. See http://jdarchive.org/player/collection/885250/view#frame/706621 for an example.

**Comment by nickkapur** [comment]
Zeega player is gone for the time being.
