### ISSUE TITLE
images dragged to be cover image of collection is not saved

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#492]
A user attempts to drag an image to become the cover image of a collection. It initially saves. However, after checking back in a few minutes on the main "collections" page, the image has not been saved and there is still no cover image. For example, user attempted to save a cover image for the following collection:

http://jdarchive.org/ja/collection/1475695

**Comment by nickkapur** [comment]
Issue appears to have been resolved.
