### ISSUE TITLE
Data ingestion command returns runtime error

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#501]
app/console zeega:persist --file_path=/home/molly/kikigaki101.json --ingestor=console and --user=427

app/console zeega:persist --file_path=/home/molly/sakura-on-sabusawa.json --ingestor=console and --user=427 --check_for_duplicates

I am running these from the /var/www/zeega directory. User 427 exists in the dev database.

**Comment by lfbrandao** [comment]
Hi @mollydesjardin, @jshapins - the command had too many arguments (the "and" shouldn't be there). The following works:

app/console zeega:persist --file_path=/home/molly/kikigaki101.json --ingestor=console --user=427
app/console zeega:persist --file_path=/home/molly/sakura-on-sabusawa.json --ingestor=console --user=427 --check_for_duplicates
