### ISSUE TITLE
Logged in users not able to save new collections

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#509]
About 5 users all had this problem in both Firefox and Chrome. In Firefox, they get a 404 Not Found error when they click on "save my collection" after dragging items into the collection box. In Chrome, simply nothing happens. These users were not able to create collections at all from the items they had dragged into the collection box.

**Comment by jshapins** [comment]
I've tested this and I experience the same issue. I'm unsure what has changed. This worked well 2 weeks ago when we/Zeega last made updates.
