### ISSUE TITLE
User not able to log in on Chrome using Windows 7

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#512]
My user (desjardin@fas.harvard.edu) is not able to log in to the site at all, either the regular UI or admin interface. Nothing happens when I click "sign in". I am using the correct ID and password. Previously, I was able to log in but where my username should have been, it said "none" and I was unable to view my profile page.

This occurred in Google Chrome on Windows 7. I had no problems logging in using Google Chrome on Mac OS 10.7.

**Comment by nickkapur** [comment]
Unable to replicate this bug, so closing for now.
