### ISSUE TITLE
modify item location on map via item page in regular UI

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#513]
Although there is a link to "edit location" under an item's map location on the item pop-up page when a user is logged in, the link doesn't work. A user would like to be able to edit the location on the item page instead of via the admin interface.

**Comment by nickkapur** [comment]
I don't see an "edit location" link anymore. Is it gone now?

**Comment by nickkapur** [comment]
Oh, I see it now.

**Comment by nickkapur** [comment]
E.J. and I decided it's probably best not to allow any logged in user to edit items. So this link is eventually going to go away. Closing this for now.
