### ISSUE TITLE
collections :: "drag to add cover image" box now overlaps with archive settings button, rendering it unclickable until a cover image is added and the page is reloaded

### ISSUE THREAD

**Issue by mollydesjardin** [Japan-Digital-Archives/Japan-Digital-Archive#514]
When a new collection is created, the "drag to add cover image box" is not in the center of the header where it used to be. Now it is overlaid above the "archive settings" link, making it unclickable. The issue is resolved when a cover image is added and the page is reloaded. This issue appears in both firefox and chrome, and has now been replicated by three different users on four different machines.

![image ishi](https://f.cloud.github.com/assets/2146722/414987/c9881e0a-ac27-11e2-8aaa-54249a74bc00.png)

**Comment by nickkapur** [comment]
Here is another screenshot:

![screen shot 2013-05-05 at 12 37 28 pm](https://f.cloud.github.com/assets/2294780/463823/245b4f68-b5a2-11e2-91cd-a8e23e176951.png)

**Comment by ebensing** [comment]
this is fixed and merged into production. 306e0bfa2056c78ce5352999873c004f1df31269
