### ISSUE TITLE
PUT issue

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#515]
We’re seeing issues with using put requests to update items. As an example, take the following request:

$.ajax({ url: "http://jdarchive.org/zeega/api/items/464188?api_key=API_KEY_HERE&id=464188&tags=" + encodeURIComponent('["shotart","japan","art","shotatrip","earthquake"]'), type: "PUT" }).success(function() alert('hi'));

(note: I’ve tried a few different ways to encode the tags, but none of them seem to work- if that is the issue here, just let me know)

This returns no error on the website- the response says everything went fine. Additionally, looking at the error log on the server, we do not see anything. However, the changes are not made. If you check the mysql either on the admin page or via the command line, you will see no updates. Additionally, the GET API will not return an updated value either.

**Comment by lfbrandao** [comment]
I believe the request is incorrect. The tags should be sent on the payload and not on the query string. 
The following example works:

$.ajax({
          type: "PUT",
          url: "http://zeega.jdarchive.org/api/items/205126?api_key=ADD-THE-API-KEY-HERE",
          data: { tags: ["jishin", "tsunami", "sougofollow"] }
        }).done(function( msg ) {
          alert( "Data Saved: " + msg );
        });

cc @ebensing

**Comment by ebensing** [comment]
Filipe,

This seems to actually be giving us an error, which is good. But it is still an error, specifically: 
NetworkError: 405 Method Not Allowed

I am using the rijs api_key, which should give us admin access on all items- correct? 

Thanks for the clarification on the request format, I think I was misreading the documentation on jquery.

**Comment by lfbrandao** [comment]
E.J., sorry to hear that this is not working yet. Is the code that is throwing the error somewhere in the repository? I tested the example above on directly on the server a while ago and using the API key, so if you could send a link to the code that is not working that would be very helpful.

**Comment by lfbrandao** [comment]
Hi @ebensing - the issue was related to the request being cross-domain and I updated the nginx config. Should be fine now, but let me know if it's still not working.

**Comment by ebensing** [comment]
looks great thanks!
