### ISSUE TITLE
Attributes ingestion issue

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#516]
If attributes is empty, it is being put in the table as ‘s:0:"";’ This doesn’t seem to cause problems on the front end, but on the admin side it blows up, saying it is an improper format. E.J. fixed this on existing items by setting any item with an attributes field equal to the above to ‘a:0:{}’ instead.

**Comment by lfbrandao** [comment]
I can't reproduce this one (made a couple of requests with null and empty attributes but didn't get the 's:0:"";’). The attributes field is a text field and it's content is not validated for correctness. This issue makes me think that you might be sending an empty string to the API and it get's saved serialized. If you send null or an empty array this shouldn't happen.

cc @ebensing

**Comment by ebensing** [comment]
Interesting. @mollydesjardin - how are you importing the items? Can you give Filipe an example of how you import the items?

We have been able to reproduce this issue using Molly's ingestion methods.

**Comment by mollydesjardin** [comment]
@ebensing @luisbrandao I'm using the code provided on the wiki, for example:

app/console zeega:persist --file_path=/home/molly/31114.json --ingestor=console --user=435 --check_for_duplicates

I also do imports not using the check_for_duplicates flag.

**Comment by ebensing** [comment]
can you post a sample file that you import?

**Comment by mollydesjardin** [comment]
@ebensing @luisbrandao I don't see a way to attach the file to this comment, so I'm going to email it to both of you.

Molly

**Comment by lfbrandao** [comment]
Hi @mollydesjardin - sorry for the late response. I looked at the file you sent me and the "attributes" is an empty string instead of an array. "attributes": "" should be replaced with "attributes": []
