### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#517]
1. server diagram
2. documentation on proxy server (including setup)
3. how to setup production server, i.e. what happens after you install ubuntu
4. how to get new database up and running (less what to do to get another RDS instance running, more how to get the schema imported and setup)
5. Setup process for solr

**Comment by lfbrandao** [comment]
1. is already on the docs (check physical architecture section)
2. the proxy server is nginx, with a standard config. need a private github repo to store the configuration and setup steps.
3. we don't have deployment scripts, but I will enumerate the main requirements. need a private github repo for this.
4. I use the export / import tool of SequelPro, but the the standard MySql dump - restore will also work. E.g. http://www.thegeekstuff.com/2008/09/backup-and-restore-mysql-database-using-mysqldump/
5. I'll add the configuration and setup steps to the private github repo

cc @ebensing
