### ISSUE TITLE
Collections :: search within collection functional

### ISSUE THREAD

**Issue by jshapins** [Japan-Digital-Archives/Japan-Digital-Archive#52]

**Comment by kanarinka** [comment]
I think the API is ignoring the 'collection' parameter right now but once that works then searching within the collection should work

**Comment by lfbrandao** [comment]
Yes; this is dependent on Issue #61. I'm working on fixing this.

**Comment by lfbrandao** [comment]
Should be fixed. Let me know if there is information missing.
