### ISSUE TITLE
collections :: unable to create new collection

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#524]
Koko reports that she is unable to create new collections. I have confirmed this issue. When I click "Create a new Collection" in the drop-down menu in the collection box, it appears to create a new collection (called "new collection 775" or some other three-digit number, as usual). You can even drag items into this new collection. However, when you click "go to collection" it takes you to a url http://jdarchive.org/en/collection/undefined and displays a 404 error. The new collection then disappears when you go back and reload, as if it were never really created, and does not show up as an unpublished collection in the admin dashboard.

**Comment by ebensing** [comment]
fixed with 7209157c49596d20220a567783360bbf3077ca2a
