### ISSUE TITLE
items :: batch replace "via:" for websites not by RIJS or other collection to "RIJS"

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#525]

**Comment by nickkapur** [comment]
Nick needs to clarify this.

**Comment by ebensing** [comment]
@nickkapur can you clarify this a bit?

**Comment by nickkapur** [comment]
@ebensing I guess I need some clarification myself. How is the "via: " for websites (on the far right in list view, usually RIJS) generated? For all websites, this should either say "via: RIJS" or else "via: National Diet Library". However, for some websites it shows the Display Name of the individual user who submitted. At first, I thought this was a problem with the "Media Creator Username" field not being set to "rijs", but in some cases, such as item # 706977, the Media Creator Username is not rijs, yet the item shows up in the live site as "via: RIJS".

The main point is we don't want the "via:" to show the Display Name of the submitter.

**Comment by nickkapur** [comment]
For example, user "Kim" (Koko) has a few websites and an image attributed to her: http://jdarchive.org/en/user/421 as do I: http://jdarchive.org/en/user/397

In the list view of a search these websites are also attributed to us, rather than to RIJS

**Comment by ebensing** [comment]
alright, I understand. New items should no longer have this problem, but I'll get the old one's switched over

**Comment by ebensing** [comment]
just fixed this, let me know if you can still find items not attributed to rijs or NDL
