### ISSUE TITLE
text input or pasted into search box is often partially obscured (especially in Japanese)

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#528]

**Comment by hsenju** [comment]
I tested this out and I think this is more of an issue with visualsearch.js than our code.
I got the same issue when pasting things into
http://documentcloud.github.io/visualsearch/
When you click outside of the searchbox, the pasted text appears in full.

kmlawson had the same issue:
#137
