### ISSUE TITLE
unpublished items other than websites show up in the database despite being unpublished

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#538]
Even non logged in users can search for and see them. Unpublished websites do not seem to show up.

**Comment by nickkapur** [comment]
Nick needs to provide examples.

**Comment by ebensing** [comment]
@nickkapur have you found any examples?

**Comment by nickkapur** [comment]
I can't recreate this bug so I am closing this issue for now. I'm guessing it got resolved when we fixed the issue of deleted items showing up. Or something!
