### ISSUE TITLE
deleted items still show up

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#539]
For example, I published an image as a test at:

http://jdarchive.org/en/item/1514361

I then deleted that item in the admin interface, yet the item is still searchable and visible on the live site.

As discussed we need to have a way to reliably delete items from both the database and the solr index.

**Comment by ebensing** [comment]
just fixed this. Had to build a script to check for it. See the config repo. solr/delete_oldsolr.py.dist
