### ISSUE TITLE
Finish up "Translate This" backend

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#547]
Hikari says the front end is finished, but is having trouble saving translations through to the db.

**Comment by ebensing** [comment]
this is now working and on production as of 6d4c83b83671bc22d19a98b69eae9dddc900c4e6

NOTE: if you save a translation and then immediately reload the page, it will look like the translation did not get saved. it takes about 1m for the SOLR index to update with the new value. Most users should not notice this
