### ISSUE TITLE
Batch recategorize item type of 311 Memories headlines from "news article" to "news headline"

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#548]
The majority of the 311 Memories headlines are still appearing as "news articles". Only the Asahi Asia & Japan Watch articles should currently be appearing as "news articles".

**Comment by ebensing** [comment]
@mollydesjardin 

can someone tell me how to select the 311 items in the database? do they all have a common attribute?

**Comment by nickkapur** [comment]
@ebensing Well the are all "via: 311 Memories" so it would probably be something like select where user_id = 311 Memories AND media type = news article. Does this make sense?

**Comment by mollydesjardin** [comment]
You should be able to select them by user_id=426. There shouldn't be any need to select by another field too, because everything by user 426 is a news headline (currently "Article").

**Comment by ebensing** [comment]
this should be fixed, let me know if you find any documents I missed.
