### ISSUE TITLE
Batch replace items with media creator username "rijs" with the media creator realname, if one exists.

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#555]
No item should have media creator username rijs.

**Comment by HakuG** [comment]
I'll take this one.

**Comment by HakuG** [comment]
Sometimes, the realname is still RIJS. Is that okay? I don't know what the goal of this one is.

**Comment by nickkapur** [comment]
@HakuG Yeah, if the realname is RIJS, than that's fine. Basically, we want to give credit to people who submitted stuff, wherever possible.
