### ISSUE TITLE
Issue to consider :: how to make YouTube videos display correctly

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#566]

**Comment by mollydesjardin** [comment]
Can you provide more detail?

**Comment by nickkapur** [comment]
For example, item 1493421 is a youtube video submitted as media type "Video" but it does not display in the popup and the thumbnail in search is wrong. Compare this to one of the Sendai Mediateque videos like item 884812. They all display correctly, but in the admin interface everything is identical, so what's the difference here?

**Comment by rchen152** [comment]
I think this issue has been resolved (https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/pull/906)
The example item now displays correctly:
http://jdarchive.org/en/item/1493421
http://jdarchive.org/en/search#q=Charlie+Brooker+on+the+Media's+Japan+Coverage&media_type=&sort=relevant&

**Comment by nickkapur** [comment]
It does! Thanks much!
