### ISSUE TITLE
Translate This :: Localize to Japanese

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#571]
Translation = 翻訳
Edit Translation = 翻訳を修正する

**Comment by nickkapur** [comment]
As discussed, other parts of popup are localized - was this hard-coded?

**Comment by ebensing** [comment]
What should "Submit Translation" be?

**Comment by nickkapur** [comment]
@ebensing Good point. Let me check with our localization team and get back to you on this.

**Comment by nickkapur** [comment]
@ebensing "Submit Translation" should just be 翻訳する, and "Submit" should be 投稿

**Comment by nickkapur** [comment]
Or we can just leave "Submit" as "Submit" as we have done elsewhere...
