### ISSUE TITLE
When sorting by oldest, Yahoo Japan photos show today's date

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#573]
This problem also appears when specifically sorting testimonials by oldest. A bunch of the recently submitted ones show todays date and are listed as the oldest. I checked several of these items in the admin, and they either have a media creation date exactly matching their date created, or else have no media creation date, so maybe that is part of the issue?

**Comment by ebensing** [comment]
I just looked into this. Very weird. It looks like it is a problem in the Zeega code somewhere. For some reason, those items are not returning a media_date_created when selected from SOLR, not sure why this would be happening, will need to investigate further.

**Comment by ebensing** [comment]
It looks like this is pretty much fixed. It seems like data in SOLR can get corrupted from time to time and you have to completely re-build the index. I'll post a full write up in the wiki later
