### ISSUE TITLE
General documentation on how to set up new dev environment, push updates, etc.

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#576]

**Comment by ebensing** [comment]
This should be done. Let me know if it doesn't look clear/concise enough. https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/wiki/Contributing-to-the-archive-source-code

**Comment by mollydesjardin** [comment]
This is really helpful, EJ. Thanks for the clear instructions!
