### ISSUE TITLE
testimonial submission form :: if user submits an image url, it gets stored in the "images" attribute as simply "Array"

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#580]
Obviously, we would want to store the actual url.

**Comment by nickkapur** [comment]
We would also want to decide what we want to do with that url. Maybe we just want to eliminate the option to enter an image url?

**Comment by ebensing** [comment]
So, the values are actually being stored correctly in the database; however, due to limitations in the symfony admin, it shows up as "Array" (because it is an array of images) rather than a proper representation. No good fix for this at the moment.
