### ISSUE TITLE
Website item pages: items 1475610 and later link to actual site, rather than internet archive site, while earlier websites link (correctly) to IA

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#589]
This is a left over issue from the site merge. We fixed this on the popups, but not on the item pages. It's the URL/URI issue. Need to correct this going forward in website submission form, as well as fix items 1475610 onward.

I'm putting this in the current milestone as I view this as rather urgent.

**Comment by ebensing** [comment]
Note: this change wont be live until we push the bookmarklet to the live site.
