### ISSUE TITLE
New Front Page :: Upon first pageload in firefox and sometimes in chrome, collections carousel shows as thin strips - problem disappears on page reload

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#594]
![picture 10](https://f.cloud.github.com/assets/2294780/863126/c86900b4-f602-11e2-9238-ef78a6cb497c.png)

**Comment by ebensing** [comment]
I noticed this as well last night, didn't have time to debug though. Would be best is @corinnecurcie could figure this out.

**Comment by corinnecurcie** [comment]
E.J. do you know why it's happening?

I can't figure it out. I'll keep looking at it though.

On Fri, Jul 26, 2013 at 12:14 PM, E.J. Bensing notifications@github.comwrote:

> I noticed this as well last night, didn't have time to debug though.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/594#issuecomment-21630988
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science
