### ISSUE TITLE
Collections :: when a collection is created items are cloned and show up double in search.

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#600]
For example, when I made some test collections, these two images were cloned four times and all show up in public search:

![image](https://f.cloud.github.com/assets/2294780/926375/47843f72-ff8a-11e2-9af7-d1a4488304f7.png)

**Comment by ebensing** [comment]
I can see this in the data, but not able to reproduce. can you do it again and list the exact steps to reproduce this error?

**Comment by ebensing** [comment]
@nickkapur any chance we can close this?

**Comment by nickkapur** [comment]
Yeah, I can't reproduce this either so closing for now.
