### ISSUE TITLE
IA Export not working

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#601]
Molly said the last time she tried to export websites to IA, all she got was a blank page, despite waiting 5 mins. Have we looked into this yet?

**Comment by ebensing** [comment]
@nickkapur Alright, this isn't working because somehow the file we had storing the last export date got blown up. Do you have any idea what the last item exported was or the date of the last export?

**Comment by nickkapur** [comment]
@ebensing I'll ask Koko.

**Comment by nickkapur** [comment]
@ebensing See Koko's reply to my email. Hopefully that's all the info we need!
