### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by hsenju** [Japan-Digital-Archives/Japan-Digital-Archive#611]
It seems our dev server has run out of space on the root directoy. Does anyone know how to fix this:

When I hit the page I got this error:
ErrorException: Warning: mkdir(): No space left on device in /var/www/hikari/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php line 137

When I got a git pull I got this error (it looks like a 100% is being used on the root directory):
remote: Counting objects: 121, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 67 (delta 46), reused 49 (delta 28)
error: unable to create temporary sha1 filename .git/objects/7f: No space left on device

Then I ran df -h and got this:
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.9G  7.5G     0 100% /
udev            819M  8.0K  819M   1% /dev
tmpfs           331M  192K  331M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            827M     0  827M   0% /run/shm
/dev/xvdb       147G  188M  140G   1% /mnt
/dev/xvdf        50G  261M   47G   1% /sftp

**Comment by ebensing** [comment]
I just cleaned up some files, should have enough room to do things now. 

As a note to everybody, try to avoid making unnecessary clones of the repo.
