### ISSUE TITLE
311 Memories :: Need to script up a chron job ASAP to harvest new headlines.

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#622]
We've missed the headlines for the past few months, so we should get this up and running as soon as we can. More info here:

http://daishinsai.pbworks.com/w/page/63228672/311%20Memories

Script is here:

https://github.com/Japan-Digital-Archives/scripts/blob/master/311.py

**Comment by ebensing** [comment]
Unfortunately, it does not look like Molly committed all the data we need. There is some "last-7-days.json" file that seems to be needed for this to run.

**Comment by ebensing** [comment]
@nickkapur Can you get in touch with Molly and see if she still has that file somewhere? Or can at least remember what it is supposed to be?

**Comment by nickkapur** [comment]
@ebensing I'm pretty sure the only file this needs to run is the one at http://agora.ex.nii.ac.jp/earthquake/201103-eastjapan/mass-media/json/last-7-days.json

This is stated in the pbworks wiki explanation.

Let me know if it's still not working!

~N

**Comment by ebensing** [comment]
ah gotcha, I swore I read the wiki entry, but I guess I must have totally missed that. I'll try and get all this up and running tomorrow.

**Comment by ebensing** [comment]
alright, I think everything should be setup. I have the script written and I tested it manually, so we have this week's stuff in there. It will run twice a week, once on Monday and once on Thursday. Let me know if it looks like nothing new is added next week.
