### ISSUE TITLE
Add Tumblr icon to front page next to Twitter and Facebook Icons, and add "News" link to "About" menu below "FAQ"

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#625]
These should link to our new "JDA News" Tumblr: http://jdarchive-news.tumblr.com/

**Comment by nickkapur** [comment]
Also, Japanese localization for "News" link should be "ブログ"

**Comment by annawada** [comment]
It loos like the Tumblr icon isn't showing up on my Chrome browser - instead there's a gray square next to the Facebook icon. 
![tumblr screenshot](https://f.cloud.github.com/assets/4721986/1201354/88e0aef0-2533-11e3-9230-273e734d2149.jpg)

**Comment by corinnecurcie** [comment]
Sorry, the logo didn't get added when I pushed. E.J. I just pushed the file and submitted a pull request - can you merge it in? I will make sure to use a personal fork next time, this was just a quick fix.
