### ISSUE TITLE
Frontpage Collections Carousel :: If title of collection is too long, it visibly spills over onto the bottom of the thumbnail.

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#632]
A minor bug, but it would be nice to clean this up.

**Comment by HakuG** [comment]
I'm taking this one too.

**Comment by nickkapur** [comment]
@HakuG @corinnecurcie 

This is not quite fixed yet. Look at the "Resurrection of Fukushima" colection currently on the front page - it's still spilling over. Reopening and reassigning to Harnek.
