### ISSUE TITLE
Tags disappear + Tags not saved

### ISSUE THREAD

**Issue by kyleparry** [Japan-Digital-Archives/Japan-Digital-Archive#637]
- I add tags to an item that already has tags, return to the item and all tags are gone
- I add tags to an items without any tags, return it and no tags visible

**Comment by ebensing** [comment]
So, generally what happens here is it takes about 5 minutes or so before the new tags are updated in the cache. Probably something we should say somewhere, but I don't think there is any scalable way to make everything instantaneous.

**Comment by kyleparry** [comment]
Interesting - I've returned to items tagged yesterday and they don't have
any.
