### ISSUE TITLE
Have to click arrow twice to advance from preview of one item to the next

### ISSUE THREAD

**Issue by kyleparry** [Japan-Digital-Archives/Japan-Digital-Archive#646]

**Comment by nickkapur** [comment]
@kyleparry You are talking about the javascript popup, right? If so, I'm unable to reproduce this error. Which browser are you using?

**Comment by kyleparry** [comment]
Yes - the popup. In Chrome. Take this collection for instance:
http://jdarchive.org/en/collection/884962

I click the first item then click either arrow (or press the left or right
key) and it doesn't advance. Press again and it does.

Looking at the Console - if it doesn't advance (from the perspective of the
user) it's actually just reloading that same item in the 'fancybox' as the
code calls it. This is visible in that the Description/Tags/Maps fields
refresh rather than staying static.

From what I gather there's something wacky going on in how the code
generates the new ID it's supposed to use when you click to move between
items.

It seems like a secondary concern - but I'm hoping it's not symptomatic of
an issue with calling in object IDs that will screw with the presentation
editor.

**Comment by nickkapur** [comment]
Okay, I've confirmed this issue! Thanks for the further explanation. We'll get this fixed.

**Comment by kyleparry** [comment]
My computer isn't a freak! Woo!

**Comment by ebensing** [comment]
@kyleparry @nickkapur the only way I'm able to reproduce this is if I click the first item, then go back (which is can't do because it is the first item) If I open the first item, then click the right arrow (or use keyboard) it works just fine.

Can you guys test again and see if it got fixed somewhere along the line?

**Comment by corinnecurcie** [comment]
It still needs two clicks to advance for every item, on my end.

**Comment by ebensing** [comment]
bleh, looks like it is a chrome only issue then. I'll try and fix it this weekend unless you want to handle it @corinnecurcie

**Comment by corinnecurcie** [comment]
It depends; have we found the import script yet? I've been poking around for it but can't find it. If I can get that, I'd rather update that so I can import the Tohoku stuff, but otherwise I can take care of this.
