### ISSUE TITLE
What would be required to scrape contents of English site of Sendai Mediateque?

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#653]
Andy wants to bring the contents on this site into our archive: http://recorder311-e.smt.jp/

He wants an assessment of what it would take and how much effort would be required.

**Comment by ebensing** [comment]
@nickkapur what does he want these items imported as? Should they be as websites or should they be the media type that they actually are? (image, video, ect)

Importing them as simple websites is pretty straightforward. If we want to do it as their native media types though, it'll be a slightly more involved script (nothing _too_ bad, but definitely take some more time)

**Comment by ebensing** [comment]
I'm going to go ahead and close this. I think we should just open a new ticket when we actually decide to do this.
