### ISSUE TITLE
Many Japanese users are still trying to access our site using Internet Explorer

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#717]
As per Google Analytics.

We may need to reconsider our policy of only supporting Firefox and Chrome.

**Comment by corinnecurcie** [comment]
IE 8, 9, 10, 11 
OR developer tools

**Comment by corinnecurcie** [comment]
find out what is broken on IE

**Comment by jcuanm** [comment]
The website seems to be working fine on IE 11. Is there something specific that it is not supporting?
![image](https://cloud.githubusercontent.com/assets/8813674/5426267/05b39736-8315-11e4-8976-c8f04d928173.png)

**Comment by meeshmon** [comment]
Did you try with earlier versions as well? People do use 10, 9, 8 and 7 as well. 
![ie versions](https://cloud.githubusercontent.com/assets/8205299/5426431/bbae2ff2-831e-11e4-9bab-2dd164cf8c86.png)

**Comment by jcuanm** [comment]
After figuring out how to use the Internet Explorer Developers Tools, I found out that the website is supported by IE 9 and 10.

**Comment by jcuanm** [comment]
However, on IE 8, I get the following error:
![image](https://cloud.githubusercontent.com/assets/8813674/5550256/a00e1f02-8b6e-11e4-9ff8-bc78a08f00d9.png)

**Comment by nickkapur** [comment]
I think if the site works fine on IE 9 through 11, than that is good enough. IE 8 is super old.
