### ISSUE TITLE
Collections: Unable to add cover image and delete items 

### ISSUE THREAD

**Issue by annawada** [Japan-Digital-Archives/Japan-Digital-Archive#719]
The "add image" box doesn't appear at the top of Collections editing page ; item "delete" buttons are overlapping with icons, making it difficult to delete items. (Chrome browser)

**Comment by nickkapur** [comment]
@annawada Hi Anna! Unfortunately I've been unable to replicate these issues. However, we have made some changes to how collections work, recently. Have you tried clearing your browser cache?

**Comment by annawada** [comment]
Hi Nick,

I had tried clearing the cache last week, but now it seems to be working
fine! I can add the cover image, although the delete buttons are still
overlapping with the website icons (a minor inconvenience).

On Mon, Jan 13, 2014 at 11:34 PM, nickkapur notifications@github.comwrote:

> @annawada https://github.com/annawada Hi Anna! Unfortunately I've been
> unable to replicate these issues. However, we have made some changes to how
> collections work, recently. Have you tried clearing your browser cache?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/719#issuecomment-32238150
> .

## 

Program Associate
North American Coordinating Council on Japanese Library Resources
Website: http://www.nccjapan.org
E-mail: annawada@nccjapan.net

**Comment by nickkapur** [comment]
Closing this for now
