### ISSUE TITLE
311 Memories Headlines :: Add Solr reset into workflow

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#729]

**Comment by corinnecurcie** [comment]
I set up a cronjob to re-index Solr once a day at around midnight, and it appears to have worked last night based on the log files so I think it's good to go. I can set it to be less often or more often, or at a different time of day if anyone thinks that would be better, but I think this is definitely better than manually re-indexing.
