### ISSUE TITLE
Map :: Sections of map not loading

### ISSUE THREAD

**Issue by annawada** [Japan-Digital-Archives/Japan-Digital-Archive#732]
![map](https://f.cloud.github.com/assets/4721986/2174044/7a251774-95aa-11e3-9c71-9e1380298975.jpg)

**Comment by nickkapur** [comment]
I have been able to reproduce this error. So strange! We'll definitely have to take a look.

**Comment by nickkapur** [comment]
This is possibly a problem with the mapbox account; we don't have the keys. I've contacted Zeega, still awaiting a response.
