### ISSUE TITLE
Content :: Add Watanave Data

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#738]

**Comment by corinnecurcie** [comment]
Hello Nick-san,
It's Hidenori Watanave.

I've shared our KML data in Google Drive.
https://drive.google.com/folderview?id=0B7uKeVg3VJZRNXZERWstcXNGVU0&usp=sharing
(If you cannot access to it, Please contact me.)

I wrote details of data in "Readme".
If you have any questions, contact me always!

I am waiting for the information of API of your jdarchive.

Thank you very much.

**Comment by corinnecurcie** [comment]
The watanave data is from Hidenori Watanave's archive about the disasters, which is built on Google Earth, here:

http://shinsai.mapping.jp/index_en.html

As you'll see, it has some pretty awesome visualizations. He gave us the Google Earth .kml files, which are basically xml files. I think I might have forwarded them to you already, but I will forward again forthwith! Basically, he has a bunch of geolocated stuff, so theoretically all we have to do is run a script on those kml files to incorporate stuff into our archive!

What we should do is have Ryo go through the archive (http://shinsai.mapping.jp/index_en.html) and see what is there that we want to add. We basically have full authority to add anything there, except possibly the Asahi stuff, where we'd need to get permission. The contact at Asahi to email about this is, I believe, Okuyama Shojiro okuyama-s@asahi.com. Assuming you decide we want to incorporate that data, Ryo can email him.

Also, you should definitely feel free to direct any and all questions to me!

**Comment by corinnecurcie** [comment]
LATITUDE AND LONGITUDE
