### ISSUE TITLE
Content :: Add NPR Data

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#741]

**Comment by nickkapur** [comment]
Go to http://www.npr.org/api/index for instructions.

You will need to register an account to use the API.

The things we want are everything that comes up after March 10, 2011 for two searches, "Japan Tsunami" and "Fukushima"

You want it to export in JSON format.

Work with @corinnecurcie  to import. Ideally we would import the sound files as sound files and the articles as news articles.

**Comment by theannielin** [comment]
When I run the API call for March 10, 2011 and "Fukushima", "There were no results that matched your query criteria." comes up. There is data for March 10, 2011 and "Japan Tsunami" though. Should I just try to import that?

**Comment by nickkapur** [comment]
@theannielin Oops, I had a typo - I mean, everything that comes up _after_ March 10, 2011.

i.e., from March 10, 2011 to the present.

**Comment by theannielin** [comment]
So, I am following the instructions on https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/wiki/Adding-data-to-the-archive on how to add data to the archive. I've scp'ed the json file into my dev server (in the var/www/zeega/ directory), and I ran "app/console zeega:persist --file_path=/var/www/zeega/nprfukushima.json --ingestor=console --user=573" (I made a new account for NPR, with the user id 573.) However, I keep getting this error:

![screen shot 2015-01-19 at 8 12 10 pm](https://cloud.githubusercontent.com/assets/5976354/5810628/92fbc4aa-a017-11e4-8d67-94a9b8b1e9f1.png)

Not sure what this means...

**Comment by theannielin** [comment]
I just saw your (@corinnecurcie ) comment on https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/739 Should I just e-mail the json files to you then?

**Comment by corinnecurcie** [comment]
Yes, that'd be fine! Thank you!

On Mon, Jan 19, 2015 at 8:20 PM, Annie Lin notifications@github.com wrote:

> I just saw your (@corinnecurcie https://github.com/corinnecurcie )
> comment on #739
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/739
> Should I just e-mail the json files to you then?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/741#issuecomment-70589485
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science

**Comment by theannielin** [comment]
I made a new account for NPR, with the user id 573.
