### ISSUE TITLE
Michinoku Shinrokuden Images :: new Michinoku photos have no location data in our archive

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#756]
When you click through to the source, they clearly have location data. However, this data appears not to have been imported into our archive, and these items do not show up on our map.

**Comment by HakuG** [comment]
Their img src is also wrong. It directs to the website instead of the image, and hence it doesn't show up. I think while downloading it, we forgot to attribute them to images and location data.

**Comment by corinnecurcie** [comment]
@nickkapur - Take, for example, this image: http://search.shinrokuden.irides.tohoku.ac.jp/shinrokuden/uuid/6ef3da30-b2f6-11e2-8831-000c2923bf22?1#entity

Yes, location data shows up on their end. However, they do not have a "lat" and "long" anywhere in the XML data. The XML for this image can be found on this XML page, if you cmd+F "6ef3da30-b2f6-11e2-8831-000c2923bf22": http://search.shinrokuden.irides.tohoku.ac.jp/webapi/oaipmh?verb=ListRecords&metadataPrefix=sdn&resumptionToken=hCHBNPNhgLuOmeqba1El7g

The "spatial" data for that image only includes a city. For it to get put in our map, we need a latitude and a longitude. So the data we need isn't there. 

@HakuG - I think we're supposed to redirect to their website, not just the image. If we just do the image, they really get no benefit from their photos being on our archive, as no traffic is directed to them. The thumbnail is a separate issue, and has nothing to do with where we link.
