### ISSUE TITLE
Item pages :: Youtube videos just show a link on item pages, rather than embedded video

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#783]
By which I mean the individual item pages and not the item popups. Ideally video would be embedded on individual item pages.

See for example: http://jdarchive.org/ja/item/1696643

**Comment by rchen152** [comment]
Ah, it looks like I missed something - when the url begins with https:// rather than http://, we still don't detect it.  Will submit a patch shortly.

**Comment by corinnecurcie** [comment]
Looks great! Released and seems to be working properly.
http://jdarchive.org/ja/item/1696643

On Sat, Oct 18, 2014 at 5:10 PM, rchen152 notifications@github.com wrote:

> Ah, it looks like I missed something - when the url begins with https://
> rather than http://, we still don't detect it. Will submit a patch
> shortly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/783#issuecomment-59629740
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science
