### ISSUE TITLE
Minor fix: Reorder item type drop-down on search page

### ISSUE THREAD

**Issue by nickkapur** [Japan-Digital-Archives/Japan-Digital-Archive#819]
Prof. Gordon would like the item types in English and Japanese to be re-ordered as follows:

all formats
exclude tweets
image
video
audio
tweet
website
document
testimonial
broadcast
news article
news headline
collection

The order up to "tweet" is the same but after that it's a different order that Prof. Gordon feels better reflects the importance of certain item types in our archive.

This is a very quick fix that anyone can do.

**Comment by corinnecurcie** [comment]
zahra

**Comment by meeshmon** [comment]
@zahramahmood, if you can quickly work on this, it's much appreciated!  Bit of pressure from the top on this issue...

**Comment by jcuanm** [comment]
@meeshmon
I will look into it.

**Comment by jcuanm** [comment]
@meeshmon 
Made the changes. Will ask Alex to update production site. As soon as Alex updates it check it out and make sure it works fine. I will close this item for now.
