### ISSUE TITLE
Popup pages not showing up ID1836094~1836101

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#823]
Popup pages are not appearing from ID 1836094 to 1836101, 8 items.

![popup page problem seeds 9 22 14](https://cloud.githubusercontent.com/assets/8831502/4363259/ea559ac8-4293-11e4-8aa8-049835d89c19.png)

**Comment by corinnecurcie** [comment]
Hi Koko,

Could you give us more information? We took a look and were able to get the popups to appear, and the images to display as well (albeit slowly).

**Comment by jdaKoko** [comment]
Corinne, I took a look and the problems were fixed.  I assigned this on 9/22. The problem may have been fixed automatically when you fixed the yahoo issue around 9/28.  Thank you very much for taking a look.
