### ISSUE TITLE
Add New Collection functionality

### ISSUE THREAD

**Issue by karashen** [Japan-Digital-Archives/Japan-Digital-Archive#832]
After dragging items to a new collection, clicking "go to collection" leads to a 404 error.

**Comment by corinnecurcie** [comment]
Hey Kara, is this happening on your dev server, or the current site? I'm not having those issues on the site.

**Comment by karashen** [comment]
This is happening on the current site. I'm not sure if it has to do with my
permission on creating collections? But I'm definitely not able to create a
collection.
