### ISSUE TITLE
Michinoku Shinrokuen (user_429) category "Unknown Format" is not appearing on the JDA search

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#836]
The Michinoku Shinrokuden collection is supposed to have documents or pdfs.  However, they are not appearing in the collection, resulting in 1179 items missing.  These are categorized under "Unknown Format".  
They all have the Media Type labled as  "Video" in the Admin Edit pages, and their item pages say "View on Yahoo Japan", but the "View on Yahoo Japan" link leads to Michinoku Shinrokuden.
i.e. http://jdarchive.org/admin/zeega/data/item/1586935/edit
i.e. http://jdarchive.org/en/item/1586935

Please take a look, some items seem to have duplicates.
I made a spread sheet for the "Unknown Format" ID numbers which I will share with you later.
Koko

**Comment by corinnecurcie** [comment]
I think this is fixed now. All the items now have the archive field listing "Michinoku Shinrokuden" instead of "Yahoo! Japan" and all the media/layer types list Document/PDF instead.

**Comment by jdaKoko** [comment]
Thank you!!
