### ISSUE TITLE
pop up page tag problem

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#838]
Tags appear in one filed in pop ups when you submit seeds using the bookmarklet.  
There is no "add a tag" function in the pop up.
The item page shows word "null" shows up in the tag section when you submit using the bookmarklet.
e.g. http://jdarchive.org/en/item/1924955

Source: アスベスト - 大震災と化学物質 ID1924955
http://jdarchive.org/ja/collection/1924934

![pop-up page_tag problem](https://cloud.githubusercontent.com/assets/8831502/4609005/71471166-5292-11e4-84a4-d5db135ace97.png)
![null in tag](https://cloud.githubusercontent.com/assets/8831502/4609077/677056fa-5294-11e4-830e-972b77e3df0c.png)

**Comment by corinnecurcie** [comment]
Hi Koko,

I am seeing the "NULL" problem and I will work on that. 

However, I was not able to replicate the issue of the "add a tag" function in the popup. Here is what it looks like when I get the item to popup (thank you for including the collection source by the way!):

![screen shot 2015-01-14 at 9 24 43 pm](https://cloud.githubusercontent.com/assets/3768712/5751594/2f545a16-9c34-11e4-9cd4-4d35f580b73e.png)

Are you still finding the popup issue? If not, I will just work on the "NULL' tag issue.

**Comment by jdaKoko** [comment]
Thank you very much again for fixing the NULL tag problem.  I am happy that tags in the pop-up show as they do.
