### ISSUE TITLE
Cannot edit a collection again after saving and reedit

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#859]
I cannot edit the explanation on my collection page after saving once and attempting to reedit.
The collection page url has # after the ID number.
I have to refresh the url to restart editing.
The image shows that when you have # in the url the yellow boxes won't appear.

![cannot edit collection](https://cloud.githubusercontent.com/assets/8831502/4695687/dc36ffac-57da-11e4-8e4d-fad8c06de907.png)

**Comment by corinnecurcie** [comment]
Hey @jdaKoko I believe this is fixed! Thank you @rchen152!!! =)
