### ISSUE TITLE
Published seeds are not appearing on the JDA search

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#863]
The User 1,RIJS, submissions after ID1927196 are not appearing on the JDA search.
The User 426, 311 Memories, items after ID1924342 are not appearing on the JDA search.

**Comment by corinnecurcie** [comment]
Hi Koko,

When you say 'published seeds' - how are you publishing them? Is this through the bookmarklet, or through the submission page on the website, or through a script?

**Comment by jdaKoko** [comment]
1.) All submissions through Bookmarklet and the submission pages are published on the Admin Dash page.  (see the attached image)

2.) I do not know how other imported items, such as 311 Memories and Michnoku items, are published.

3.) I checked the User 1 items on the JDA search.  Now the RIJS website items are appearing on the JDA search.

4.) The User 426, 311 Memories, items from ID1924342 to 1927909 are appearing on the JDA search, but after ID 1931433 are NOT appearing on the search.
![publishing websites](https://cloud.githubusercontent.com/assets/8831502/4965600/61a40062-678b-11e4-9b1f-4cbc61131c95.png)

**Comment by nickkapur** [comment]
Seems to have been resolved.
