### ISSUE TITLE
MAPS BROKEN 

### ISSUE THREAD

**Issue by corinnecurcie** [Japan-Digital-Archives/Japan-Digital-Archive#867]
again

**Comment by corinnecurcie** [comment]
FIX IT

**Comment by meeshmon** [comment]
The CGA says that they can't connect to the Solr running in Amazon's cloud at 174.129.31.158 on port 8080. Probably need to restart Solr? It could be an issue on our end.

**Comment by HakuG** [comment]
That seems to be right. I couldn't find anything wrong with the code.
Restarting Solr (no idea how to do that) is the best plan of action.

**Comment by corinnecurcie** [comment]
I just restarted solr but haven't noticed a change. I also changed our
security settings in the same way we had to with Matt and MapD, to fix that
connectivity issue, but still not seeing anything. It's strange, becauase
Solr is fine for us. We are getting pings of 1ms and our search is fine.
It's all about the connectivity elsewhere, which is strange. The only
recent changes are the Fukushima data changes/import for the popup issue.

On Tue, Nov 4, 2014 at 4:31 PM, HakuG notifications@github.com wrote:

> That seems to be right. I couldn't find anything wrong with the code.
> Restarting Solr (no idea how to do that) is the best plan of action.
> On Nov 4, 2014 4:28 PM, "meeshmon" notifications@github.com wrote:
> 
> > The CGA says that they can't connect to the Solr running in Amazon's
> > cloud
> > at 174.129.31.158 on port 8080. Probably need to restart Solr? It could
> > be
> > an issue on our end.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/867#issuecomment-61717670>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/867#issuecomment-61718167
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science

**Comment by corinnecurcie** [comment]
It looks like it was CGA's server, per Steve's email this morning:

"The server responding to requests at http://geops.cga.harvard.edu:8080 hung.  After restarting the server application the map layer appeared.  Let me know if you see any problems.  If not, I'll close the ticket tomorrow."

Closing this issue. We can reopen if something happens again,
