### ISSUE TITLE
API :: page parameter ignored

### ISSUE THREAD

**Issue by jamesburns** [Japan-Digital-Archives/Japan-Digital-Archive#87]
http://dev.jdarchive.org/zeega/web/api/search?&view_type=list&content=image&page=1&r_items=1&r_tags=1&r_itemswithcollections=0

and

http://dev.jdarchive.org/zeega/web/api/search?&view_type=list&content=image&page=2&r_items=1&r_tags=1&r_itemswithcollections=0

appear to return same results

**Comment by lfbrandao** [comment]
Fixed
