### ISSUE TITLE
Yahoo images ID 1-20001 are missing from the admin dashboard.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#883]
I just noticed that Yahoo images ID 1-20001 are missing from the admin dashboard and JDA search.
http://jdarchive.org/ja/user/3

**Comment by corinnecurcie** [comment]
Hey Koko,

Yes, we became aware of this last night and are working on it!

On Fri, Dec 5, 2014 at 5:36 PM, jdaKoko notifications@github.com wrote:

> I just noticed that Yahoo images ID 1-20001 are missing from the admin
> dashboard and JDA search.
> http://jdarchive.org/ja/user/3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/883
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science
