### ISSUE TITLE
Kazuko Sakaguchi could not drag items to her collection

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#886]
This may be the same as #718.

On 12/16, Ms. Sakaguchi tried to make a collection.  She could not drag items to her collection.  While she was trying to add items, the collection box icon (a rectangle with an arrow toward a dotted rectangle, see the attached image) never went away although she refreshed the page many times. In my experience, refreshing the page erases the collection box icon and makes it possible to drag items. After adding items, the box usually turns yellow when the dragging process finishes.  In her case, the box never changed yellow.
This phenomenon ususally and frequently happens when there are more than 100 items in one collection. In Ms. Sakaguchi's case she only had a few items in the collection.   She was using Chrome on a Microsoft base computer.  I only use Mac, so I do not know if this is a machine orented problem or not.

![collection box](https://cloud.githubusercontent.com/assets/8831502/5493836/5179471a-86bc-11e4-936f-bb0a8bcbd83e.png)

**Comment by nickkapur** [comment]
I took a look at this and was unable to replicate this bug on two different Microsoft machines running chrome. Kazuko often had trouble with things like this in the past. Without a more specific rundown of the problem, we may have to chalk this up to a temporary situation on Kazuko's specific machine, although we should keep any eye out for any future recurrence. Closing this issue for now but #718 remains open.
