### ISSUE TITLE
Youtube videos submitted using bookmarklet are not showing up on pop-ups and there is not scroll-down function.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#887]
I will attach the edit pages of youtube video submissions and the corresponding fancy box snapshots.  One is Prof. Watanabe's submission, which does not have any problems.  The other one is my youtube submission using bookmarklet.  The youtube via bookmarklet pop-ups are not showing in the fancy box and the scoroll down function is not there, either.  
![koko s video submission using bookmarklet](https://cloud.githubusercontent.com/assets/8831502/5498273/abe26d84-86ea-11e4-8764-fb289bbc7b22.png)
![prof watanabe s video submission](https://cloud.githubusercontent.com/assets/8831502/5498274/ae634bb4-86ea-11e4-9fc1-8244e71c1fa6.png)

**Comment by HakuG** [comment]
Look at the thing in the bottom: 
"Last Exported Seed ID: 1938111 if it has a higher ID, it has not been sent to IA."

I'm guessing we have to run Solr? @corinnecurcie, any idea?

**Comment by jdaKoko** [comment]
This is not a Solr problem.  The Last Export Seed ID number only applies to the category website, in which Uri*s with waybackportion are the admin edit pages.

In this issue, the problems are occuring in the video submissions through bookmarklet.  Video submissions using bookmarklet do not have waybackportion in their uri\* so they are not sent to IA.  

It seems that Youtube submissions using bookmarklet are treated the same as video submissions throuth API like Prof. Watanabe's    However, bookmarklet submitted videos are not showing up in the fancy box.

**Comment by corinnecurcie** [comment]
I believe that the problem is possibly because the videos submitted through the Bookmarklet are getting categorized as "Layer Type: outside-Youtube". 

However, currently no youtube videos are showing up in the fancybox for me... so I'm having a hard time testing this. Are you able to see Youtube videos in the fancybox currently, Koko?

**Comment by jdaKoko** [comment]
I still cannot see a video in the fancy.
The below is the example.
The attached image item is not out-sideYoutube.
http://jdarchive.org/admin/zeega/data/item/1935005/edit
The item page does not show the video, either.
http://jdarchive.org/ja/item/1935005
![bookmarklet youtube submission](https://cloud.githubusercontent.com/assets/8831502/5622665/f50817ce-9514-11e4-8ccb-744c573a4188.png)

**Comment by nickkapur** [comment]
Weirdly, I can see the Watanave youtube videos in fancybox, but they have no thumbnail. But other youtube videos that _do_ have a thumbnail do not show up in fancybox.

See this link: http://jdarchive.org/en/search#media_type=Video&sort=media-date-desc&

**Comment by jdaKoko** [comment]
FYI
Youtubes on Sakura on Project and Sendai Mediatheque have thumnails but the videos show up in facybox.
http://jdarchive.org/ja/user/427#media_type=Video&sort=relevant&
http://jdarchive.org/en/user/4
Those videos are imported by collaborators.
They are not submitted by bookmarklet.

**Comment by corinnecurcie** [comment]
@rchen152 - Hey Rebecca I know you had some success with our videos the last time, is there any chance you could take a look at this?

**Comment by rchen152** [comment]
Hmm, so it looks like there are two separate things going on:
1) When the layer type or uri is wrong, the fancybox and item page videos don't show up.
2) When the the thumbnail uri is missing, the thumbnail doesn't show up.  (Conversely, if there is thumbnail uri, the thumbnail shows up regardless of whether the actual video is working.)
I'll see what I can do.

**Comment by jdaKoko** [comment]
YouTube items are complicated!
Items with the category "Website" and layer type "Website" are sent to Internet Archive for archiving and were submitted through the contribute page, so Youtube urls which have the category "Website" are not part of #887, the problem I first mentioned.  Those seeds do not have thumnail urls and they should have waybackportion in their Uri_.   The bookmarklet submissions and API related Youtube items are in the category "video" and layertype YouTube.  
Anyway, YouTube items with wayback portion uri_ look great on pop-ups in the fancy box and item pages.  Thank you!
However, there is one flaw in the pop-ups in the view source link in the wayback uri\* youtube items.  I will submit another issue later.

**Comment by jdaKoko** [comment]
FYI
Initially, the bookmarklet-submitted YouTubes items had the Youtube url in their uri.  Jessica fixed the bookmarklet Youtube uri  on Oct, 2014 to be consistant with YouTube uri with Sakura on Project, Recorder 311. Now, the uris are showing only Youtube Ids, such as cMc1uBYImhg.

Bookmarklet Youtube submission between ID 1536049 and1935021 have Youtube url uris.
However, any of the bookmarklet submissions do not play videos in their fancybox nor item pages regardless of Uri having Youtube urls or Youtube id.

Hmm, I hope I explained this clearly to you about this problem.

**Comment by rchen152** [comment]
I think this update fixes the issue: https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/pull/906

In Chrome and IE on my laptop, the following now all display properly:
http://jdarchive.org/en/item/1942410 (video on item page)
http://jdarchive.org/ja/item/1935005 (video on item page)
http://jdarchive.org/en/search#media_type=Video&sort=media-date-desc& (thumbnails and fancybox videos)

**Comment by corinnecurcie** [comment]
Thank you so much @rchen152! Awesome work! =)

@jdaKoko could you confirm if the issue is resolved and close the issue if so? Thank you! =)

**Comment by jdaKoko** [comment]
Great! Thank you very much.
