### ISSUE TITLE
Home logo rendering and transparency

### ISSUE THREAD

**Issue by kmlawson** [Japan-Digital-Archives/Japan-Digital-Archive#89]
The home page logo:

http://dev.jdarchive.org/staging/web/images/jda_eng_logo_white.png

is not fully transparent (white pixels remain) and aliasing a bit too blurry.

Modify or recreate at smaller size and font?

The Japanese version of the logo is almost unreadable.

**Comment by jshapins** [comment]
Konrad, do you think we could the source Illustrator or Photoshop file for the logo? To register on the black, we made this one super quickly.
