### ISSUE TITLE
After the 1/1/15 fix on the admin dashboard, something went wrong with item pages.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#890]
The url, http://jdarchive.org/admin/zeega/data/item/1944691/edit was submitted on 1/4/15. The url, http://jdarchive.org/admin/zeega/data/item/1945195/edit, was imported from 311 memory.
The item pages are not showing up properly.

The item pages prior to 12/30/14 do not have problems. i.e.
http://jdarchive.org/en/item/1938767
http://jdarchive.org/en/item/1194846

**Comment by corinnecurcie** [comment]
Hi Koko,

I think this was also fixed with the re-index. The pages look good to me, so I'm going to close it. I'll wait for you to confirm the other issues though.

**Comment by jdaKoko** [comment]
Thank you again! Super!
