### ISSUE TITLE
Prof. Hidenori Watanabe's imports (ID1946365~1947290) are not appearing in his collection page

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#892]
Prof. Watanabe's image imports came on 1/7/15, 1126 total . Only 200 items (ID1946165~1946364) are appearing in his collection page.  http://jdarchive.org/en/user/566.  
The total item should be 1935, not 1010. SOLAR reset problem?

**Comment by rchen152** [comment]
I'm currently in the middle of re-indexing Solr, which should hopefully fix this problem.

**Comment by rchen152** [comment]
Yep, after the re-index, all 1126 of the images are showing up:
http://jdarchive.org/en/user/566#q=weathernews.jp&media_type=Image&sort=relevant&

**Comment by jdaKoko** [comment]
Thank you very much for the quick-fix! I can even see his latest addtion(173 images) to the collection.
