### ISSUE TITLE
Filtering system change request

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#907]
Please change flitering system Uri to Attribution Uri on the admin page so that the admin page users can search with live or dead but known urls.

1.)YouTube submissions do not have domain part (I mean http://www.youtube.com/) in uri .
2.) Website submissions do have waybackportion in their uri 
3.) Yahoo image items have uri  such as http://photoarchive.c.yimg.jp/res/emgphoto-0237/093/71237_sr.jpg but the live link is http://archive.shinsai.yahoo.co.jp/entry/71237/.

![filterlin change request](https://cloud.githubusercontent.com/assets/8831502/5794714/4650a370-9f48-11e4-873a-1711eca79928.png)

**Comment by corinnecurcie** [comment]
I added attribution_uri so that you can search with either one. Is this acceptable?

**Comment by jdaKoko** [comment]
Yes!  Thank you again. I will tell Anna about the change.
