### ISSUE TITLE
YouTube items with category "Website" : View Source should link to wayback page 

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#908]
YouTube items with category "Website" should have internet archive wayback page links in the "View Source"  Right now, they are linked to JDA user plus Youtube id that result error pages.
Their item pages and fancy boxes do not have any problem at all, beautiful!  The IA-archived videos play nicely.
![category website youtube item problem](https://cloud.githubusercontent.com/assets/8831502/5794739/1e46b602-9f49-11e4-819b-6def9e851e1c.png)

**Comment by rchen152** [comment]
The View Source link is working now:
http://jdarchive.org/en/user/1#q=heroes+of+japan+earthquake+and+tsunami&media_type=&sort=relevant&

**Comment by jdaKoko** [comment]
Thank you again, Rebecca.   The IT Crowd rocksl
