### ISSUE TITLE
Add Hidenori Watanave to our partners page  

### ISSUE THREAD

**Issue by meeshmon** [Japan-Digital-Archives/Japan-Digital-Archive#916]
Hidenori Watanave and the Great East Japan Earthquake Archive　http://shinsai.mapping.jp/

**Comment by theannielin** [comment]
Is there a description or something I can add to to partners page for Hidenori Watanave and the Great East Japan Earthquake Archive? I only put the titles (for my latest pull request).
Also, if there are descriptions, are there also translations?
Thanks!

**Comment by meeshmon** [comment]
Thanks Annie for this. I will ask Watanave to provide us with the description of the archive in both Japanese and English. I will let you know when I receive it.

**Comment by jcuanm** [comment]
Is this still an issue or can we close this?

**Comment by meeshmon** [comment]
You can close the issue.
Thanks

On Aug 12, 2016, at 14:42, jcuanm notifications@github.com wrote:

Is this still an issue or can we close this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/916#issuecomment-239527524,
or mute the thread
