### ISSUE TITLE
bookmarklet language problem

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#923]
When I tried to submit aseed using bookmarklet, I get a message saying "Please select a language before submitting" although I selected the language before submitting.
I was using the browser Chrome.

**Comment by horak** [comment]
@theannielin think you could try to replicate and try to figure this out?

**Comment by jcuanm** [comment]
I tried to recreate the problem and found nothing. Could you elaborate a bit more? Any specific conditions?

**Comment by jdaKoko** [comment]
@jcuanm @meeshmon 
Javier, thank you for working on the issue.
I do not see the problem,either.  I used the bookmarklet using Safari, Firefox and Chrome.  I did not have any problem submitting items.  Let me close the issue right now.  When I see the problem again, I will ask you to look at the bookmarklet.

**Comment by jcuanm** [comment]
@meeshmon 
Sure, no problem.
