### ISSUE TITLE
Add additional language fields to Bookmarklet

### ISSUE THREAD

**Issue by meeshmon** [Japan-Digital-Archives/Japan-Digital-Archive#942]
Add "French" and "Others" to the bookmarklet language field.

**Comment by jcuanm** [comment]
Programs that might need to be changed: seedSubmit.html.twig, widget.html.twig, form.js, messages.en.xliff and messages,ja.xliff.

Further analysis required

**Comment by jcuanm** [comment]
Just found the translation for "French" and "Others" in Chinese characters

**Comment by meeshmon** [comment]
Javier, thanks. For French you can put ”フランス語" and for others you can put "その他"

**Comment by jcuanm** [comment]
Found this Chinese characters that may go more in line with the ones already there since we are not using any kanji.

French  法国語              Other   其他

What do you think?

**Comment by meeshmon** [comment]
Javier,
You are probably looking at Chinese Chinese not Chinese characters used in Japanese.

**Comment by jcuanm** [comment]
Ok. Got it.

**Comment by jcuanm** [comment]
The new languages were added to the bookmarklet. I am going to close this issue. Please, let me know if you have further requests for languages.
