### ISSUE TITLE
Should we get rid of the "drag items here to add to your collection" box if user is not logged in? 

### ISSUE THREAD

**Issue by corinnecurcie** [Japan-Digital-Archives/Japan-Digital-Archive#951]
Currently, the right-hand box for collection building pops up, but users can't actually drag anything there because they're not recognized as users (logged in). So it just looks like the feature doesn't work. Alternatively, we could have text appear saying "Please log in to drag items to your collection!" or something.

**Comment by meeshmon** [comment]
@corinnecurcie How difficult would it be to let any user (without logging in) to tryout making a collection to see how the archive work? I was wondering if it would potentially get more registered users if we let any user to build collection and give a pop-up prompt something like "register to the JDA to save your collection 'click link' to login page" when the user try going to his/her collection page.

**Comment by corinnecurcie** [comment]
Okay I actually realized, it already does let not-logged-in users make collections! When you're not logged in, you can drag items over, and then a small link comes up at the bottom of the box saying "Save Collection", which prompts you to log in, and then when you log in, it does save that collection! What a handy feature, haha. So do you think this is good? My original worry in making the issue is that this DIDN'T happen, so I think we can close this actually, unless you think the "Save Collection" text should be different or more obvious.
