### ISSUE TITLE
Please add names to the team page

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#956]
To http://jdarchive.org/en/team
Please add two names to the JDA team pages under webseed curation.

Kae Nakahashi, Showa Boston Institute for Language and Culture
Yumiko Takeda, Showa Boston Institute for Language and Culture

To http://jdarchive.org/ja/team
Kae Nakahashi（昭和ボストン　中橋佳恵）
Yumiko Takeda（昭和ボストン　竹田有美子）

**Comment by meeshmon** [comment]
@rchen152 @theannielin @zahramahmood @jcuanm 
 I know it is the finals' week but if one of you can quickly take care of this,
it'd be much appreciated!

**Comment by rchen152** [comment]
I'm done with finals, so I'll have this done in a moment!

**Comment by jdaKoko** [comment]
Thank you very much!

**Comment by rchen152** [comment]
Should be done with https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/pull/981!

**Comment by jdaKoko** [comment]
@jcuanm @rchen152 @meeshmon 

To http://jdarchive.org/en/team
Please add two names to the JDA team pages under webseed curation.

Kanami Ohno, Showa Boston Institute for Language and Culture
Maho Yanagisawa, Showa Boston Institute for Language and Culture

To http://jdarchive.org/ja/team
Kanami Ohno（昭和ボストン　大野奏美）
Maho Yanagisawa（昭和ボストン　柳澤真帆）

**Comment by rchen152** [comment]
The new names have been added!  If they look correct, this issue can be closed.

**Comment by horak** [comment]
Looks go to me!

**Comment by jdaKoko** [comment]
Thank you very much!
