### ISSUE TITLE
Cannot close for the "New Users" pop-up.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#982]
The new addition of the "New User" pop-up does not close when I click "X" in Chrome. It is a big problem when you need to contribute using the contribute page.
![close function not working](https://cloud.githubusercontent.com/assets/8831502/7667683/86081980-fbd7-11e4-9893-67642e65a8e9.png)

**Comment by meeshmon** [comment]
@rchen152 @jcuanm @theannielin @zahramahmood 
One of you please work on this as soon as you can. Thanks!

**Comment by jdaKoko** [comment]
Clearing browsing data in Chrome sloved this problem.
