### ISSUE TITLE
images from collections disappeared.

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#985]
37 images from collections disappeared.  ![images disappeared](https://cloud.githubusercontent.com/assets/8831502/8048954/223c88da-0e26-11e5-82cb-2e1964fc3bf8.png)
There are two phenomena:
1. Those images are from Yahoo Images; http://jdarchive.org/en/user/3.
My record says that the number of yahoo images on 5/17/15 was 40,061, but it has changed to 40,044.
2. All the collections for which the image disappeared had http://static.zeega.org/staging/items/... in their thumbnail urls.
The attached image is the filtering method for my collection in the admin dash.  The result comes up to 42 items, and some thumbnail urls do not have http://static.zeega.org/staging/items/.
![filter kim](https://cloud.githubusercontent.com/assets/8831502/8049224/783bad84-0e2a-11e5-9711-4e7e057610d0.png)
If you cannot restore the images, I will add them back manually. I'm actually more worried about the total number of Yahoo images.

**Comment by horak** [comment]
Ok i'll check this out!

**Comment by corinnecurcie** [comment]
jdarchive.org/admin/dashboard, as noted here
https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/wiki/Adding-data-to-the-archive#viewing-data-through-admin-dashboard
!

On Wed, Jun 10, 2015 at 7:46 AM, Alex Horak notifications@github.com
wrote:

> Ok i'll check this out, what's the admin dash url?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/985#issuecomment-110780664
> .

## 

Corinne Curcie
Harvard University
Class of 2015
Computer Science

**Comment by horak** [comment]
@jdaKoko, let's discuss this on Thursday so I have a better idea of what's going on here.

**Comment by jdaKoko** [comment]
I added the missing images manually to the admin pages.  Thank you!
