### ISSUE TITLE
Team Page, http://jdarchive.org/en/team, changes requested

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#988]
1. Kae Nakanishi finished her internship on 6/19/15. Therefore, her name should be listed under Team Alumni.
   English page: http://jdarchive.org/en/team
   Please change from
   Web Seed Curation: Kae Nakahashi, Showa Boston Institute for Language and Culture

to Team Alumni
Kae Nakahashi, Showa Boston Institute for Language and Culture: Web Seed Curation

Japanese page: http://jdarchive.org/ja/team
From コンテンツ開発
ウェブシード　キュレーション：Kae Nakahashi（昭和ボストン　中橋佳恵） 
To  チームの卒業者
Kae Nakahashi（昭和ボストン　中橋佳恵）: ウェブシード　キュレーション
1. Add to Interaction Design and Development
   Project Technical Lead: Alex Horax  
   プロジェクト技術部リーダー：Alex Horax（アレックス・ホラックス）
2. Move to "Project Technical Lead: Corinne Curcie" to Team Alumni, "Corinne Curci:Technical Lead"

プロジェクト技術部リーダー：Corinne Curcie（コリン・カーシー）
To  チームの卒業者
Corinne Curcie（コリン・カーシー）:プロジェクト技術部リーダー

**Comment by meeshmon** [comment]
@rchen152 @jcuanm @theannielin @zahramahmood 
Can one of you take care of this?

**Comment by jcuanm** [comment]
I can take care of this

On Sat, Jun 20, 2015 at 1:41 PM, meeshmon notifications@github.com wrote:

> @rchen152 https://github.com/rchen152 @jcuanm
> https://github.com/jcuanm @theannielin https://github.com/theannielin
> @zahramahmood https://github.com/zahramahmood
> Can one of you take care of this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/988#issuecomment-113818522
> .

## 

Javier Cuan

**Comment by jcuanm** [comment]
I was able to remove and add her name onto the page. However, I hard-coded
her name onto the alumni page, which looks really ugly within the code.
I'll need to learn how to use the translation system that twig is using,
before I can make the code prettier. But the job is done!

On Sat, Jun 20, 2015 at 1:41 PM, meeshmon notifications@github.com wrote:

> @rchen152 https://github.com/rchen152 @jcuanm
> https://github.com/jcuanm @theannielin https://github.com/theannielin
> @zahramahmood https://github.com/zahramahmood
> Can one of you take care of this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Japan-Digital-Archives/Japan-Digital-Archive/issues/988#issuecomment-113818522
> .

## 

Javier Cuan

**Comment by jdaKoko** [comment]
@jcuanm 
I do not see any change in the team page. Could you take a look?
http://jdarchive.org/en/team
![no_change in team page](https://cloud.githubusercontent.com/assets/8831502/8275730/bc14b0ba-1879-11e5-98c3-143588be8541.png)

**Comment by meeshmon** [comment]
@horak Can you push the request?

**Comment by horak** [comment]
@jdaKoko, you won't be able to see those changes until I merge them. @meeshmon, I just made some code recommendations @jcuanm should fix before I merge.

**Comment by jcuanm** [comment]
I was able to successfully add her name onto the page using translations. Should I commit my changes?
![image](https://cloud.githubusercontent.com/assets/8813674/8288866/acb649ea-18cd-11e5-90a5-e02b657b8135.png)
