### ISSUE TITLE
Solr reset request: please reindex 

### ISSUE THREAD

**Issue by jdaKoko** [Japan-Digital-Archives/Japan-Digital-Archive#994]
There is a similar problem to #863&#941
Published seeds on 7/11/15 (>1982126)are not appearing in the JDA search.

**Comment by horak** [comment]
Ok I re-indexed, let me know if that fixes this.

**Comment by jdaKoko** [comment]
Thank you very much! It is fixed now.

**Comment by horak** [comment]
Great!

**Comment by jdaKoko** [comment]
The same problems as #863&#941.
@horak 
It might be a good idea to re-index Solr because 9/10 & 9/14 imports (944 items) from 311 Memories are not appearing on the search.
http://jdarchive.org/ja/user/426
User 426 imports should be automatically updated.

**Comment by horak** [comment]
Re-indexed!

**Comment by jdaKoko** [comment]
@meeshmon @horak 
Thank you for reindexing, but the user 426's total item number has not changed.  
http://jdarchive.org/ja/user/426 should be 402409 not 401465 .  
Is this a new problem?

**Comment by horak** [comment]
@jdaKoko, difficult to tell. Before we can investigate this exactly, we're going to try to figure out problem over in #996 which seems to be causing all the problems, like this. I'm closing this for now.
